import pathlib

workspace_root = pathlib.Path(__file__).resolve().parents[1]
target = workspace_root / "backend" / "src" / "ai" / "destination-catalog.data.ts"

prefecture_data = [
  {
    "keywords": ["清水寺", "Kiyomizu"],
    "spots": [
      {"place": "清水寺", "area": "京都市東山区", "category": "SIGHTSEEING", "desc": "舞台から京都市街を一望し国宝の伽藍を巡る。", "stay": 90},
      {"place": "二年坂・三年坂", "area": "京都市東山区", "category": "SHOPPING", "desc": "石畳の坂道で京雑貨と和菓子店をはしご。", "stay": 60},
      {"place": "八坂庚申堂", "area": "京都市東山区", "category": "SIGHTSEEING", "desc": "色とりどりのくくり猿で知られる寺で写真撮影。", "stay": 30},
      {"place": "高台寺", "area": "京都市東山区", "category": "SIGHTSEEING", "desc": "秀吉ゆかりの庭園と茶室を巡りライトアップも鑑賞。", "stay": 60},
      {"place": "圓徳院", "area": "京都市東山区", "category": "SIGHTSEEING", "desc": "北政所ねねが過ごした方丈で枯山水庭園を眺める。", "stay": 45},
      {"place": "祇園花見小路", "area": "京都市東山区", "category": "SIGHTSEEING", "desc": "茶屋が並ぶ花街を散策し夜の灯りを楽しむ。", "stay": 50},
      {"place": "安井金比羅宮", "area": "京都市東山区", "category": "SIGHTSEEING", "desc": "縁切り縁結び碑を潜って祈願する。", "stay": 35},
      {"place": "京都国立博物館", "area": "京都市東山区", "category": "OTHER", "desc": "仏像や名品を収蔵する明治建築の美術館を鑑賞。", "stay": 70},
      {"place": "茶寮都路里 祇園本店", "area": "京都市東山区", "category": "FOOD", "desc": "抹茶パフェと和スイーツで休憩。", "stay": 45},
      {"place": "スターバックス コーヒー 京都二寧坂ヤサカ茶屋店", "area": "京都市東山区", "category": "FOOD", "desc": "町家造りのカフェで畳席と限定メニューを楽しむ。", "stay": 40},
    ],
  },
  {
    "keywords": ["浅草寺", "浅草", "Senso-ji", "Asakusa"],
    "spots": [
      {"place": "浅草寺", "area": "台東区", "category": "SIGHTSEEING", "desc": "雷門から本堂まで参拝し江戸情緒を味わう。", "stay": 75},
      {"place": "仲見世通り", "area": "台東区", "category": "SHOPPING", "desc": "人形焼や揚げまんじゅうなど下町グルメを食べ歩き。", "stay": 45},
      {"place": "浅草文化観光センター", "area": "台東区", "category": "SIGHTSEEING", "desc": "展望テラスからスカイツリーと浅草の街並みを眺める。", "stay": 35},
      {"place": "浅草花やしき", "area": "台東区", "category": "OTHER", "desc": "日本最古の遊園地でレトロなアトラクションを体験。", "stay": 60},
      {"place": "浅草神社", "area": "台東区", "category": "SIGHTSEEING", "desc": "三社祭で知られる社で参拝。", "stay": 30},
      {"place": "浅草演芸ホール", "area": "台東区", "category": "OTHER", "desc": "落語や漫才の寄席を生で鑑賞。", "stay": 70},
      {"place": "ホッピー通り", "area": "台東区", "category": "FOOD", "desc": "煮込みとホッピーで昼飲み文化を体験。", "stay": 45},
      {"place": "雷門 三定", "area": "台東区", "category": "FOOD", "desc": "天保年間創業の天ぷらをいただく。", "stay": 50},
      {"place": "隅田公園", "area": "台東区", "category": "REST", "desc": "隅田川沿いの遊歩道で桜とタワー夜景を楽しむ。", "stay": 40},
      {"place": "東京クルーズ 浅草乗り場", "area": "台東区", "category": "MOVE", "desc": "水上バスで隅田川クルーズへ出発。", "stay": 45},
    ],
  },
  {
    "keywords": ["東京スカイツリー", "Skytree"],
    "spots": [
      {"place": "東京スカイツリー 天望デッキ", "area": "墨田区", "category": "SIGHTSEEING", "desc": "地上450mから東京の景色を一望する。", "stay": 80},
      {"place": "東京スカイツリー 天望回廊", "area": "墨田区", "category": "SIGHTSEEING", "desc": "チューブ状の回廊で空中散歩を楽しむ。", "stay": 40},
      {"place": "すみだ水族館", "area": "墨田区", "category": "OTHER", "desc": "都市型水族館でペンギンやクラゲ展示を鑑賞。", "stay": 60},
      {"place": "東京ソラマチ イーストヤード", "area": "墨田区", "category": "SHOPPING", "desc": "ご当地グルメと雑貨が集まるモールで買い物。", "stay": 50},
      {"place": "郵政博物館", "area": "墨田区", "category": "OTHER", "desc": "切手と通信の歴史を体験型展示で学ぶ。", "stay": 45},
      {"place": "東京ミズマチ", "area": "墨田区", "category": "SHOPPING", "desc": "高架下のカフェやベーカリーで休憩。", "stay": 40},
      {"place": "牛嶋神社", "area": "墨田区", "category": "SIGHTSEEING", "desc": "三輪鳥居が特徴的な古社を参拝。", "stay": 30},
      {"place": "向島百花園", "area": "墨田区", "category": "SIGHTSEEING", "desc": "江戸期の花園で季節の草花と茶屋を楽しむ。", "stay": 50},
      {"place": "隅田川テラス", "area": "墨田区", "category": "REST", "desc": "川沿いの遊歩道でタワーを眺めつつ散策。", "stay": 35},
      {"place": "東武博物館", "area": "墨田区", "category": "OTHER", "desc": "鉄道シミュレーターや歴代車両を見学。", "stay": 55},
    ],
  },
  {
    "keywords": ["伏見稲荷", "Fushimi Inari"],
    "spots": [
      {"place": "伏見稲荷大社 千本鳥居", "area": "京都市伏見区", "category": "SIGHTSEEING", "desc": "朱色の鳥居トンネルをくぐりながら参拝。", "stay": 70},
      {"place": "伏見稲荷参道商店街", "area": "京都市伏見区", "category": "SHOPPING", "desc": "いなり寿司やきつねうどんを食べ歩き。", "stay": 45},
      {"place": "稲荷山山頂展望台", "area": "京都市伏見区", "category": "SIGHTSEEING", "desc": "京都市街を一望できるハイキングコース終点。", "stay": 60},
      {"place": "祢ざめ家", "area": "京都市伏見区", "category": "FOOD", "desc": "創業200年の川魚料理で鰻やう巻きを味わう。", "stay": 50},
      {"place": "東福寺", "area": "京都市東山区", "category": "SIGHTSEEING", "desc": "通天橋や枯山水庭園で紅葉を鑑賞。", "stay": 60},
      {"place": "泉涌寺", "area": "京都市東山区", "category": "SIGHTSEEING", "desc": "皇室ゆかりの御寺で静かな境内を散策。", "stay": 50},
      {"place": "伏見稲荷駅", "area": "京都市伏見区", "category": "MOVE", "desc": "駅前で土産を買いつつ次の目的地へ移動。", "stay": 30},
      {"place": "乃木神社", "area": "京都市伏見区", "category": "SIGHTSEEING", "desc": "乃木希典夫妻を祀る社で勝運祈願。", "stay": 35},
      {"place": "月桂冠大倉記念館", "area": "京都市伏見区", "category": "OTHER", "desc": "酒蔵ツアーで伏見の水と日本酒文化を学ぶ。", "stay": 55},
      {"place": "京阪祇園四条駅", "area": "京都市東山区", "category": "MOVE", "desc": "祇園方面へのアクセス拠点として利用する。", "stay": 25},
    ],
  },
  {
    "keywords": ["嵐山", "Arashiyama"],
    "spots": [
      {"place": "嵐山 竹林の小径", "area": "京都市右京区", "category": "SIGHTSEEING", "desc": "青竹が続く遊歩道で幻想的な朝を迎える。", "stay": 45},
      {"place": "渡月橋", "area": "京都市右京区", "category": "SIGHTSEEING", "desc": "桂川の流れと山並みを背景に記念撮影。", "stay": 40},
      {"place": "天龍寺", "area": "京都市右京区", "category": "SIGHTSEEING", "desc": "曹源池庭園を巡り世界遺産の禅寺を鑑賞。", "stay": 60},
      {"place": "嵐山よしむら", "area": "京都市右京区", "category": "FOOD", "desc": "鴨川を望む蕎麦処でランチを取る。", "stay": 50},
      {"place": "嵯峨野トロッコ列車", "area": "京都市右京区", "category": "MOVE", "desc": "保津川沿いを走る観光列車で渓谷美を楽しむ。", "stay": 60},
      {"place": "大河内山荘庭園", "area": "京都市右京区", "category": "SIGHTSEEING", "desc": "俳優 大河内傳次郎の山荘庭園で抹茶休憩。", "stay": 50},
      {"place": "常寂光寺", "area": "京都市右京区", "category": "SIGHTSEEING", "desc": "多宝塔と苔むす参道で静寂を味わう。", "stay": 40},
      {"place": "キモノフォレスト", "area": "京都市右京区", "category": "SIGHTSEEING", "desc": "京友禅のポールが灯るインスタ映えスポットを散策。", "stay": 30},
      {"place": "嵯峨野観光鉄道 トロッコ嵐山駅", "area": "京都市右京区", "category": "MOVE", "desc": "レトロな駅舎で列車を待ちながら土産を購入。", "stay": 35},
      {"place": "嵐山モンキーパークいわたやま", "area": "京都市西京区", "category": "SIGHTSEEING", "desc": "放し飼いのニホンザルと展望台からの景色を楽しむ。", "stay": 55},
    ],
  },
  {
    "keywords": ["道頓堀", "Dotonbori"],
    "spots": [
      {"place": "道頓堀グリコサイン前", "area": "大阪市中央区", "category": "SIGHTSEEING", "desc": "ネオン煌めく戎橋で記念撮影。", "stay": 30},
      {"place": "黒門市場", "area": "大阪市中央区", "category": "FOOD", "desc": "新鮮な海鮮串やフルーツジュースを食べ歩き。", "stay": 45},
      {"place": "法善寺横丁", "area": "大阪市中央区", "category": "SIGHTSEEING", "desc": "石畳の路地で苔むした水掛不動尊を参拝。", "stay": 35},
      {"place": "なんばグランド花月", "area": "大阪市中央区", "category": "OTHER", "desc": "吉本新喜劇や漫才ステージで笑いを満喫。", "stay": 90},
      {"place": "かに道楽 道頓堀本店", "area": "大阪市中央区", "category": "FOOD", "desc": "動く巨大カニ看板で知られる本店で会席を味わう。", "stay": 70},
      {"place": "心斎橋筋商店街", "area": "大阪市中央区", "category": "SHOPPING", "desc": "全長600mのアーケードでファッションをチェック。", "stay": 50},
      {"place": "アメリカ村 三角公園", "area": "大阪市中央区", "category": "SIGHTSEEING", "desc": "若者カルチャーが集う広場でストリートアートを観察。", "stay": 30},
      {"place": "道頓堀川遊歩道 とんぼりリバーウォーク", "area": "大阪市中央区", "category": "SIGHTSEEING", "desc": "川沿いの遊歩道で夜景と屋台船を楽しむ。", "stay": 40},
      {"place": "ドン・キホーテ 道頓堀店 観覧車", "area": "大阪市中央区", "category": "OTHER", "desc": "楕円形の観覧車に乗り街を見渡す。", "stay": 35},
      {"place": "自由軒 難波本店", "area": "大阪市中央区", "category": "FOOD", "desc": "名物カレーと生卵を混ぜる老舗洋食の味。", "stay": 40},
    ],
  },
  {
    "keywords": ["北海道", "札幌市", "Sapporo", "Hokkaido"],
    "spots": [
      {"place": "札幌市時計台", "area": "札幌市", "category": "SIGHTSEEING", "desc": "木造の時計塔内部で札幌開拓の歴史を学ぶ。", "stay": 40},
      {"place": "大通公園", "area": "札幌市", "category": "SIGHTSEEING", "desc": "季節の花壇と噴水が続くシンボルパークを散策。", "stay": 45},
      {"place": "さっぽろテレビ塔", "area": "札幌市", "category": "SIGHTSEEING", "desc": "展望台から石狩平野と大通公園を一望。", "stay": 40},
      {"place": "北海道庁旧本庁舎", "area": "札幌市", "category": "SIGHTSEEING", "desc": "赤れんが庁舎で開拓期の資料を鑑賞。", "stay": 35},
      {"place": "すすきの", "area": "札幌市", "category": "SHOPPING", "desc": "ネオン街で海鮮やジンギスカンの名店をハシゴ。", "stay": 60},
      {"place": "モエレ沼公園", "area": "札幌市", "category": "SIGHTSEEING", "desc": "イサム・ノグチ設計のアートパークで丘と噴水を巡る。", "stay": 70},
      {"place": "サッポロビール博物館", "area": "札幌市", "category": "OTHER", "desc": "醸造の歴史解説を聴き工場直送の一杯を味わう。", "stay": 60},
      {"place": "白い恋人パーク", "area": "札幌市", "category": "OTHER", "desc": "ガラス張りの工場見学と限定スイーツを楽しむ。", "stay": 55},
      {"place": "北海道大学植物園", "area": "札幌市", "category": "SIGHTSEEING", "desc": "学術庭園で高山植物と温室コレクションを観察。", "stay": 50},
      {"place": "札幌市中央卸売市場 場外市場", "area": "札幌市", "category": "FOOD", "desc": "朝どれの海鮮丼や土産を市場でまとめ買い。", "stay": 60},
    ],
  },
  {
    "keywords": ["札幌市中央区", "札幌中心部", "Central Sapporo"],
    "spots": [
      {"place": "札幌もいわ山ロープウェイ", "area": "札幌市中央区", "category": "SIGHTSEEING", "desc": "山麓駅からゴンドラに乗り札幌の大夜景を望む山頂へ。", "stay": 50},
      {"place": "札幌市円山動物園", "area": "札幌市中央区", "category": "OTHER", "desc": "ホッキョクグマ舎など人気展示を巡る市立動物園。", "stay": 70},
      {"place": "北海道神宮", "area": "札幌市中央区", "category": "SIGHTSEEING", "desc": "原生林に囲まれた北海道開拓の総鎮守を参拝する。", "stay": 40},
      {"place": "円山公園", "area": "札幌市中央区", "category": "REST", "desc": "桜並木と池を巡れる市民の憩いスポットで散歩。", "stay": 45},
      {"place": "札幌市資料館", "area": "札幌市中央区", "category": "OTHER", "desc": "旧控訴院の洋館で芸術展示と札幌の歩みを鑑賞。", "stay": 40},
      {"place": "中島公園", "area": "札幌市中央区", "category": "REST", "desc": "菖蒲池と日本庭園を備えたオアシスでボート遊び。", "stay": 50},
      {"place": "豊平館", "area": "札幌市中央区", "category": "SIGHTSEEING", "desc": "明治の洋風ホテル建築を公開展示で見学。", "stay": 35},
      {"place": "サッポロファクトリー", "area": "札幌市中央区", "category": "SHOPPING", "desc": "レンガ造りのアトリウムでショップとブルワリーを満喫。", "stay": 55},
      {"place": "JRタワー展望室 T38", "area": "札幌市中央区", "category": "SIGHTSEEING", "desc": "地上160mの展望室から大通と石狩平野を一望。", "stay": 40},
      {"place": "札幌ら～めん共和国", "area": "札幌市中央区", "category": "FOOD", "desc": "道内各地のラーメン店が集まるフードテーマパークで食べ比べ。", "stay": 45},
    ],
  },
  {
    "keywords": ["札幌市南区", "定山渓", "Minami Sapporo"],
    "spots": [
      {"place": "札幌芸術の森美術館", "area": "札幌市南区", "category": "OTHER", "desc": "森に囲まれた館で現代美術とクラフト展を鑑賞。", "stay": 60},
      {"place": "札幌芸術の森 野外美術館", "area": "札幌市南区", "category": "SIGHTSEEING", "desc": "広大な森に点在する彫刻作品を歩いて巡る。", "stay": 55},
      {"place": "滝野すずらん丘陵公園", "area": "札幌市南区", "category": "SIGHTSEEING", "desc": "花畑と渓谷アクティビティが揃う国営公園で一日遊ぶ。", "stay": 80},
      {"place": "定山渓温泉 足のふれあい太郎の湯", "area": "札幌市南区", "category": "REST", "desc": "無料足湯に浸かり渓谷の湯けむりを楽しむ。", "stay": 35},
      {"place": "豊平峡温泉", "area": "札幌市南区", "category": "REST", "desc": "源泉かけ流しの大露天風呂と名物スパイスカレーを堪能。", "stay": 70},
      {"place": "藻岩山スキー場", "area": "札幌市南区", "category": "OTHER", "desc": "市街地夜景を眺めながら楽しめるナイタースキー場。", "stay": 60},
      {"place": "八剣山ワイナリー", "area": "札幌市南区", "category": "FOOD", "desc": "果樹園を併設するワイナリーで試飲とショップ巡り。", "stay": 45},
      {"place": "真駒内セキスイハイムアイスアリーナ", "area": "札幌市南区", "category": "OTHER", "desc": "国際大会も行われる屋内リンクでアイスショーやイベントを鑑賞。", "stay": 60},
      {"place": "札幌市豊平川さけ科学館", "area": "札幌市南区", "category": "OTHER", "desc": "サケの生態展示と孵化体験を学べる科学館。", "stay": 45},
      {"place": "定山渓神社", "area": "札幌市南区", "category": "SIGHTSEEING", "desc": "森に囲まれた社で温泉街の守り神に参拝する。", "stay": 30},
    ],
  },
  {
    "keywords": ["小樽市", "小樽運河", "Otaru"],
    "spots": [
      {"place": "小樽運河", "area": "小樽市", "category": "SIGHTSEEING", "desc": "石造倉庫群とガス灯が並ぶ散策路をクルーズとともに楽しむ。", "stay": 50},
      {"place": "小樽オルゴール堂 本館", "area": "小樽市", "category": "SHOPPING", "desc": "アンティークオルゴールの実演と土産選びを満喫。", "stay": 45},
      {"place": "北一硝子 三号館", "area": "小樽市", "category": "SHOPPING", "desc": "吹きガラス工房とカフェを併設した人気店を見学。", "stay": 40},
      {"place": "ルタオ本店", "area": "小樽市", "category": "FOOD", "desc": "名物ドゥーブルフロマージュをティールームで味わう。", "stay": 35},
      {"place": "旧日本郵船小樽支店", "area": "小樽市", "category": "SIGHTSEEING", "desc": "重要文化財のクラシカルな船会社ビルを見学。", "stay": 40},
      {"place": "小樽市総合博物館 運河館", "area": "小樽市", "category": "OTHER", "desc": "港町の歴史資料と鉄道展示を鑑賞。", "stay": 45},
      {"place": "にしん御殿 小樽貴賓館", "area": "小樽市", "category": "SIGHTSEEING", "desc": "豪商青山家の木造建築でにしん漁の繁栄を学ぶ。", "stay": 50},
      {"place": "小樽住吉神社", "area": "小樽市", "category": "SIGHTSEEING", "desc": "石段の参道と拝殿を巡り海上安全を祈る。", "stay": 30},
      {"place": "祝津パノラマ展望台", "area": "小樽市", "category": "SIGHTSEEING", "desc": "ニシン漁場と日本海を見晴らす展望台。", "stay": 35},
      {"place": "小樽三角市場", "area": "小樽市", "category": "FOOD", "desc": "朝獲れ海鮮丼や干物が並ぶ市場食堂街で食事。", "stay": 40},
    ],
  },
  {
    "keywords": ["函館市", "五稜郭", "Hakodate"],
    "spots": [
      {"place": "五稜郭公園", "area": "函館市", "category": "SIGHTSEEING", "desc": "星形城郭の堀沿いを歩き桜や紅葉を鑑賞。", "stay": 60},
      {"place": "五稜郭タワー", "area": "函館市", "category": "SIGHTSEEING", "desc": "展望室から五稜郭の幾何学的な全景を眺める。", "stay": 40},
      {"place": "函館山ロープウェイ 山頂展望台", "area": "函館市", "category": "SIGHTSEEING", "desc": "夜景で有名な山頂デッキから津軽海峡を一望。", "stay": 50},
      {"place": "金森赤レンガ倉庫", "area": "函館市", "category": "SHOPPING", "desc": "ベイエリアのレンガ倉庫群で雑貨とスイーツを巡る。", "stay": 55},
      {"place": "函館ハリストス正教会", "area": "函館市", "category": "SIGHTSEEING", "desc": "異国情緒あふれるドーム屋根の教会内部を見学。", "stay": 35},
      {"place": "八幡坂", "area": "函館市", "category": "SIGHTSEEING", "desc": "石畳坂の頂上から函館港を望むビュースポット。", "stay": 30},
      {"place": "函館朝市 どんぶり横丁市場", "area": "函館市", "category": "FOOD", "desc": "活イカや海鮮丼が並ぶ市場食堂街で朝食。", "stay": 45},
      {"place": "湯の川温泉 湯巡り舞台", "area": "函館市", "category": "REST", "desc": "足湯と足蒸しを備えた温泉街の休憩スポット。", "stay": 35},
      {"place": "立待岬", "area": "函館市", "category": "SIGHTSEEING", "desc": "断崖から津軽海峡と函館山を一望。", "stay": 40},
      {"place": "函館市北方民族資料館", "area": "函館市", "category": "OTHER", "desc": "アイヌと北方民族の生活文化資料を鑑賞。", "stay": 45},
    ],
  },
  {
    "keywords": ["旭川市", "Asahikawa"],
    "spots": [
      {"place": "旭山動物園", "area": "旭川市", "category": "OTHER", "desc": "行動展示で動物の躍動感を間近に感じる人気動物園。", "stay": 80},
      {"place": "旭川市科学館 サイパル", "area": "旭川市", "category": "OTHER", "desc": "宇宙や極地をテーマにした体験型展示を楽しむ。", "stay": 55},
      {"place": "常磐公園", "area": "旭川市", "category": "REST", "desc": "池と花壇が整備された市民公園で四季の景観を味わう。", "stay": 40},
      {"place": "平和通買物公園", "area": "旭川市", "category": "SHOPPING", "desc": "日本初の恒久歩行者天国でカフェと雑貨店を巡る。", "stay": 45},
      {"place": "旭川市博物館", "area": "旭川市", "category": "OTHER", "desc": "アイヌ文化や上川地方の自然史を詳しく学ぶ。", "stay": 50},
      {"place": "雪の美術館", "area": "旭川市", "category": "OTHER", "desc": "氷の回廊と音楽堂で雪の世界観を体感。", "stay": 45},
      {"place": "旭川ラーメン村", "area": "旭川市", "category": "FOOD", "desc": "名店8軒が集合するテーマ施設で醤油ラーメンを食べ比べ。", "stay": 40},
      {"place": "男山酒造り資料館", "area": "旭川市", "category": "OTHER", "desc": "上川盆地の酒造りの歴史と試飲コーナーを楽しむ。", "stay": 45},
      {"place": "北鎮記念館", "area": "旭川市", "category": "SIGHTSEEING", "desc": "旧陸軍第七師団ゆかりの史料館で屯田兵の歴史を知る。", "stay": 40},
      {"place": "上川神社", "area": "旭川市", "category": "SIGHTSEEING", "desc": "常磐公園の杜に鎮座する社で旅の安全を祈願。", "stay": 30},
    ],
  },
  {
    "keywords": ["富良野市", "美瑛町", "Furano", "Biei"],
    "spots": [
      {"place": "ファーム富田", "area": "空知郡中富良野町", "category": "SIGHTSEEING", "desc": "ラベンダー畑と温室を回り彩り豊かな丘陵を散策。", "stay": 60},
      {"place": "青い池", "area": "上川郡美瑛町", "category": "SIGHTSEEING", "desc": "水面に立つカラマツとコバルトブルーの湖面を鑑賞。", "stay": 40},
      {"place": "四季彩の丘", "area": "上川郡美瑛町", "category": "SIGHTSEEING", "desc": "花畑とパノラマロードをバギーやカートで巡る。", "stay": 50},
      {"place": "白ひげの滝", "area": "上川郡美瑛町", "category": "SIGHTSEEING", "desc": "白金温泉に注ぐ滝とコバルトブルーの渓流を眺める。", "stay": 30},
      {"place": "ニングルテラス", "area": "富良野市", "category": "SHOPPING", "desc": "森の中のログハウス群でクラフトショップをはしご。", "stay": 45},
      {"place": "富良野チーズ工房", "area": "富良野市", "category": "OTHER", "desc": "製造見学とチーズ・バター作り体験で酪農文化に触れる。", "stay": 45},
      {"place": "富良野ワインハウス", "area": "富良野市", "category": "FOOD", "desc": "自社ワインとチーズフォンデュを丘陵レストランで味わう。", "stay": 50},
      {"place": "ふらのマルシェ", "area": "富良野市", "category": "SHOPPING", "desc": "地元野菜とスイーツを集めたモールでお土産探し。", "stay": 40},
      {"place": "十勝岳望岳台", "area": "上川郡美瑛町", "category": "SIGHTSEEING", "desc": "活火山と上富良野の街並みを一望する展望台でハイキング。", "stay": 45},
      {"place": "富良野・美瑛ノロッコ号", "area": "富良野市", "category": "MOVE", "desc": "夏季運行の観光列車でラベンダー畑をのんびり眺める。", "stay": 35},
    ],
  },
  {
    "keywords": ["帯広市", "十勝", "Obihiro", "Tokachi"],
    "spots": [
      {"place": "帯広競馬場（ばんえい十勝）", "area": "帯広市", "category": "OTHER", "desc": "世界唯一のばんえい競馬を観戦し迫力あるそり引きを体験。", "stay": 70},
      {"place": "六花亭 帯広本店", "area": "帯広市", "category": "FOOD", "desc": "限定スイーツと喫茶限定メニューで老舗菓子店の味を満喫。", "stay": 45},
      {"place": "柳月スイートピア・ガーデン", "area": "河東郡音更町", "category": "FOOD", "desc": "工場併設カフェで焼きたて三方六や十勝小豆デザートを味わう。", "stay": 45},
      {"place": "帯広百年記念館", "area": "帯広市", "category": "OTHER", "desc": "開拓から現代までの十勝の歴史と生活を学ぶ博物館。", "stay": 50},
      {"place": "真鍋庭園", "area": "帯広市", "category": "SIGHTSEEING", "desc": "世界の樹木を集めた庭園で季節の植栽とカフェを楽しむ。", "stay": 50},
      {"place": "帯広市緑ヶ丘公園", "area": "帯広市", "category": "REST", "desc": "彫刻の森と展望台を備えた市民公園でのんびり散策。", "stay": 40},
      {"place": "とかちむら", "area": "帯広市", "category": "SHOPPING", "desc": "競馬場併設のマルシェで十勝チーズとクラフトを買い集める。", "stay": 40},
      {"place": "道の駅おとふけ なつぞらのふる里", "area": "河東郡音更町", "category": "SHOPPING", "desc": "小麦や豆を使った惣菜・ベーカリーが揃う大型道の駅。", "stay": 45},
      {"place": "ガーデンスパ十勝川温泉", "area": "河東郡音更町", "category": "REST", "desc": "モール温泉のスパとフードホールでリゾート気分を味わう。", "stay": 60},
      {"place": "豚丼のぶたはげ 帯広本店", "area": "帯広市", "category": "FOOD", "desc": "炭火焼の豚丼に秘伝のタレを絡めて十勝名物を堪能。", "stay": 35},
    ],
  },
  {
    "keywords": ["釧路市", "阿寒湖", "Kushiro", "Akan"],
    "spots": [
      {"place": "釧路湿原展望台", "area": "釧路市", "category": "SIGHTSEEING", "desc": "木道を歩きながらタンチョウが舞う湿原の大パノラマを望む。", "stay": 60},
      {"place": "釧路市立博物館", "area": "釧路市", "category": "OTHER", "desc": "湿原形成やアイヌ文化を学べる地元密着ミュージアム。", "stay": 50},
      {"place": "和商市場 勝手丼", "area": "釧路市", "category": "FOOD", "desc": "好きな具材を盛る勝手丼で港町ならではの海鮮を味わう。", "stay": 45},
      {"place": "幣舞橋", "area": "釧路市", "category": "SIGHTSEEING", "desc": "世界三大夕日と称される夕景を橋の欄干彫刻と共に眺める。", "stay": 30},
      {"place": "釧路フィッシャーマンズワーフMOO", "area": "釧路市", "category": "SHOPPING", "desc": "海産物やカフェが集まる複合施設でお土産探し。", "stay": 40},
      {"place": "釧路湿原ノロッコ号", "area": "釧路市", "category": "MOVE", "desc": "夏季限定の観光列車で蛇行する釧路川と湿原を車窓から鑑賞。", "stay": 35},
      {"place": "阿寒湖アイヌコタン", "area": "釧路市", "category": "SIGHTSEEING", "desc": "木彫や舞踊ステージでアイヌ文化を体験できる集落。", "stay": 55},
      {"place": "阿寒湖遊覧船", "area": "釧路市", "category": "MOVE", "desc": "マリモ育成地や景勝地をめぐる定期船で湖上クルーズ。", "stay": 45},
      {"place": "阿寒湖温泉 足湯", "area": "釧路市", "category": "REST", "desc": "湖畔の足湯で硫黄泉に浸かり旅の疲れを癒やす。", "stay": 30},
      {"place": "道の駅阿寒丹頂の里", "area": "釧路市", "category": "SHOPPING", "desc": "タンチョウ観察施設を併設した道の駅で特産品を購入。", "stay": 40},
    ],
  },
  {
    "keywords": ["網走市", "知床", "Abashiri", "Shiretoko"],
    "spots": [
      {"place": "博物館 網走監獄", "area": "網走市", "category": "OTHER", "desc": "旧監獄建築と流刑史を学べる屋外博物館をじっくり見学。", "stay": 70},
      {"place": "オホーツク流氷館", "area": "網走市", "category": "OTHER", "desc": "マイナス15度の体験室で本物の流氷やクリオネを観察。", "stay": 45},
      {"place": "オホーツク流氷砕氷船おーろら", "area": "網走市", "category": "MOVE", "desc": "冬季限定の砕氷クルーズで白い海原を割って進む迫力を体感。", "stay": 60},
      {"place": "能取岬", "area": "網走市", "category": "SIGHTSEEING", "desc": "断崖と草原が広がる岬で灯台とオホーツク海を望む。", "stay": 40},
      {"place": "道の駅 流氷街道網走", "area": "網走市", "category": "SHOPPING", "desc": "流氷ドラフトや海産土産を扱う港沿いの拠点。", "stay": 35},
      {"place": "網走湖畔温泉", "area": "網走市", "category": "REST", "desc": "湖畔リゾートの天然温泉で碧い湖面と夕陽を楽しむ。", "stay": 50},
      {"place": "知床五湖", "area": "斜里郡斜里町", "category": "SIGHTSEEING", "desc": "高架木道やガイドツアーで原生林と湖沼を散策。", "stay": 60},
      {"place": "知床観光船おーろら", "area": "斜里郡斜里町", "category": "MOVE", "desc": "断崖や滝を海上から見上げるウトロ発着のクルーズ。", "stay": 55},
      {"place": "ウトロ温泉 公衆浴場", "area": "斜里郡斜里町", "category": "REST", "desc": "知床旅の拠点で硫黄泉に浸かりながらオホーツク海を眺める。", "stay": 35},
      {"place": "斜里町立知床博物館", "area": "斜里郡斜里町", "category": "OTHER", "desc": "流氷やヒグマに関する資料で知床の自然を学ぶ。", "stay": 45},
    ],
  },
  {
    "keywords": ["青森県", "青森市", "Aomori"],
    "spots": [
      {"place": "青森県観光物産館アスパム", "area": "青森市", "category": "SIGHTSEEING", "desc": "最上階展望台から八甲田連峰と港を眺望。", "stay": 45},
      {"place": "ねぶたの家 ワ・ラッセ", "area": "青森市", "category": "OTHER", "desc": "迫力あるねぶたの実物展示と制作工程を体験。", "stay": 60},
      {"place": "青函連絡船メモリアルシップ八甲田丸", "area": "青森市", "category": "SIGHTSEEING", "desc": "船内に保存された歴史資料を巡り海路の記憶を辿る。", "stay": 55},
      {"place": "青森県立美術館", "area": "青森市", "category": "OTHER", "desc": "奈良美智作品やシャガールの舞台背景を鑑賞。", "stay": 60},
      {"place": "三内丸山遺跡", "area": "青森市", "category": "SIGHTSEEING", "desc": "縄文集落跡で竪穴住居と復元体験を楽しむ。", "stay": 70},
      {"place": "A-FACTORY", "area": "青森市", "category": "SHOPPING", "desc": "シードル工房を眺めながら土産と軽食を味わう。", "stay": 45},
      {"place": "浅虫温泉 ゆ～さ浅虫", "area": "青森市", "category": "REST", "desc": "海を望む展望足湯で旅の疲れを癒やす。", "stay": 40},
      {"place": "合浦公園", "area": "青森市", "category": "SIGHTSEEING", "desc": "津軽海峡を望む湖畔で松林の遊歩道を散歩。", "stay": 35},
      {"place": "青森魚菜センター", "area": "青森市", "category": "FOOD", "desc": "のっけ丼スタイルで旬の海鮮を自分好みに盛り付ける。", "stay": 50},
      {"place": "青森ベイブリッジ展望広場", "area": "青森市", "category": "SIGHTSEEING", "desc": "ライトアップされた大橋と港湾夜景を撮影。", "stay": 30},
    ],
  },
  {
    "keywords": ["岩手県", "盛岡市", "Morioka"],
    "spots": [
      {"place": "盛岡城跡公園", "area": "盛岡市", "category": "SIGHTSEEING", "desc": "石垣と堀が残る城跡で四季の風景を楽しむ。", "stay": 45},
      {"place": "石割桜", "area": "盛岡市", "category": "SIGHTSEEING", "desc": "巨岩を割って咲く天然記念物の桜を観賞。", "stay": 20},
      {"place": "盛岡八幡宮", "area": "盛岡市", "category": "SIGHTSEEING", "desc": "朱塗りの社殿と参道の灯籠が美しい総鎮守。", "stay": 40},
      {"place": "もりおか歴史文化館", "area": "盛岡市", "category": "OTHER", "desc": "チャグチャグ馬コや盛岡の城下町史を学ぶ。", "stay": 50},
      {"place": "岩手銀行赤レンガ館", "area": "盛岡市", "category": "SIGHTSEEING", "desc": "辰野金吾設計の洋風建築で金融史展示を見学。", "stay": 35},
      {"place": "盛岡てづくり村", "area": "盛岡市", "category": "OTHER", "desc": "南部鉄器や木工の職人実演を間近で体験。", "stay": 70},
      {"place": "啄木新婚の家", "area": "盛岡市", "category": "SIGHTSEEING", "desc": "石川啄木ゆかりの住居で文学資料に触れる。", "stay": 30},
      {"place": "材木町よ市", "area": "盛岡市", "category": "SHOPPING", "desc": "地元農産物とクラフト品が並ぶストリートマーケット。", "stay": 45},
      {"place": "ぴょんぴょん舎 稲荷町本店", "area": "盛岡市", "category": "FOOD", "desc": "名物盛岡冷麺を石焼ビビンバと合わせて味わう。", "stay": 50},
      {"place": "白龍本店", "area": "盛岡市", "category": "FOOD", "desc": "創業店のじゃじゃ麺で好みの味変を楽しむ。", "stay": 40},
    ],
  },
  {
    "keywords": ["宮城県", "仙台市", "Sendai"],
    "spots": [
      {"place": "仙台城跡", "area": "仙台市", "category": "SIGHTSEEING", "desc": "本丸跡から仙台市街と太平洋を望む。", "stay": 50},
      {"place": "瑞鳳殿", "area": "仙台市", "category": "SIGHTSEEING", "desc": "伊達政宗公の廟所で極彩色の装飾を鑑賞。", "stay": 45},
      {"place": "定禅寺通", "area": "仙台市", "category": "SIGHTSEEING", "desc": "ケヤキ並木のプロムナードを散歩しカフェに立ち寄る。", "stay": 40},
      {"place": "せんだいメディアテーク", "area": "仙台市", "category": "OTHER", "desc": "現代建築の館内で企画展とライブラリーを回遊。", "stay": 60},
      {"place": "仙台市博物館", "area": "仙台市", "category": "OTHER", "desc": "伊達家資料と地域史を映像展示で学ぶ。", "stay": 55},
      {"place": "仙台うみの杜水族館", "area": "仙台市", "category": "OTHER", "desc": "大水槽とイルカショーで海の生態を満喫。", "stay": 70},
      {"place": "仙台朝市", "area": "仙台市", "category": "SHOPPING", "desc": "旬の鮮魚とずんだ菓子を買い歩く市民の台所。", "stay": 45},
      {"place": "仙台市天文台", "area": "仙台市", "category": "OTHER", "desc": "プラネタリウムと展示で宇宙の最新知識を吸収。", "stay": 60},
      {"place": "勾当台公園", "area": "仙台市", "category": "REST", "desc": "芝生広場でフェスやイベント露店を楽しむ。", "stay": 35},
      {"place": "牛たん炭焼 利久 本店", "area": "仙台市", "category": "FOOD", "desc": "厚切り牛たん定食を仙台味噌と共に味わう。", "stay": 50},
    ],
  },
  {
    "keywords": ["秋田県", "秋田市", "Akita"],
    "spots": [
      {"place": "千秋公園", "area": "秋田市", "category": "SIGHTSEEING", "desc": "久保田城跡の堀と桜を歩き四季の彩りに浸る。", "stay": 45},
      {"place": "久保田城御隅櫓", "area": "秋田市", "category": "SIGHTSEEING", "desc": "再建櫓の展望室から市街地と日本海を望む。", "stay": 35},
      {"place": "秋田県立美術館", "area": "秋田市", "category": "OTHER", "desc": "藤田嗣治の大壁画と建築美を楽しむ。", "stay": 60},
      {"place": "赤れんが郷土館", "area": "秋田市", "category": "OTHER", "desc": "銀行建築を利用した郷土資料館で歴史散策。", "stay": 50},
      {"place": "秋田市民市場", "area": "秋田市", "category": "SHOPPING", "desc": "ハタハタ寿司やいぶりがっこを買い込む。", "stay": 40},
      {"place": "エリアなかいち", "area": "秋田市", "category": "SHOPPING", "desc": "複合施設でクラフトショップとカフェを巡る。", "stay": 45},
      {"place": "秋田市大森山動物園", "area": "秋田市", "category": "OTHER", "desc": "希少動物展示と足湯を備えた丘陵動物園を散策。", "stay": 70},
      {"place": "ポートタワー・セリオン", "area": "秋田市", "category": "SIGHTSEEING", "desc": "高さ143mの展望室から秋田港と男鹿半島を望む。", "stay": 40},
      {"place": "秋田駅ビル トピコ", "area": "秋田市", "category": "SHOPPING", "desc": "県産品アンテナショップで限定菓子を購入。", "stay": 35},
      {"place": "佐藤養助 秋田店", "area": "秋田市", "category": "FOOD", "desc": "喉越しの良い稲庭うどんを二味のつけだれで楽しむ。", "stay": 45},
    ],
  },
  {
    "keywords": ["山形県", "山形市", "Yamagata"],
    "spots": [
      {"place": "霞城公園", "area": "山形市", "category": "SIGHTSEEING", "desc": "山形城跡の土塁と桜並木を眺める。", "stay": 45},
      {"place": "山形県郷土館 文翔館", "area": "山形市", "category": "OTHER", "desc": "英国風建築の旧県庁舎で明治の行政資料を学ぶ。", "stay": 50},
      {"place": "山寺 立石寺", "area": "山形市", "category": "SIGHTSEEING", "desc": "千段を超える石段を登り奥の院から絶景を望む。", "stay": 70},
      {"place": "宝珠山立石寺 根本中堂", "area": "山形市", "category": "SIGHTSEEING", "desc": "建立千年を超える堂内で読経の響きを聴く。", "stay": 35},
      {"place": "山形県立博物館", "area": "山形市", "category": "OTHER", "desc": "火山灰に覆われた縄文の女神像など県内資料を鑑賞。", "stay": 55},
      {"place": "七日町御殿堰", "area": "山形市", "category": "SHOPPING", "desc": "蔵造りのショップ群で地酒とクラフトを探す。", "stay": 40},
      {"place": "ぐっと山形", "area": "山形市", "category": "SHOPPING", "desc": "県内特産品が揃う物産館で果物スイーツを試食。", "stay": 45},
      {"place": "蔵王温泉大露天風呂", "area": "山形市", "category": "REST", "desc": "渓流沿いの硫黄泉で乳白色の湯に浸かる。", "stay": 60},
      {"place": "山形まなび館", "area": "山形市", "category": "OTHER", "desc": "旧校舎を活用した交流施設で企画展とカフェを楽しむ。", "stay": 40},
      {"place": "そば処 三津屋", "area": "山形市", "category": "FOOD", "desc": "板そばと山形だしを味わいローカル食文化に触れる。", "stay": 45},
    ],
  },
  {
    "keywords": ["福島県", "福島市", "Fukushima"],
    "spots": [
      {"place": "花見山公園", "area": "福島市", "category": "SIGHTSEEING", "desc": "里山を彩る花木を周遊し多彩な景観を撮影。", "stay": 50},
      {"place": "福島県立美術館", "area": "福島市", "category": "OTHER", "desc": "岸田劉生やモネ作品を中心に近代美術を鑑賞。", "stay": 55},
      {"place": "福島稲荷神社", "area": "福島市", "category": "SIGHTSEEING", "desc": "鳥居が並ぶ境内で商売繁盛の御札を授かる。", "stay": 35},
      {"place": "飯坂温泉 鯖湖湯", "area": "福島市", "category": "REST", "desc": "共同浴場の熱湯につかり昔ながらの温泉文化を体感。", "stay": 40},
      {"place": "福島市民家園", "area": "福島市", "category": "SIGHTSEEING", "desc": "移築古民家をめぐり会津・中通りの暮らしを知る。", "stay": 60},
      {"place": "こむこむ館", "area": "福島市", "category": "OTHER", "desc": "子ども科学展示とプラネタリウムを親子で楽しむ。", "stay": 50},
      {"place": "旧廣瀬座", "area": "福島市", "category": "SIGHTSEEING", "desc": "明治の芝居小屋建築を見学し舞台裏に立つ。", "stay": 30},
      {"place": "道の駅ふくしま", "area": "福島市", "category": "SHOPPING", "desc": "桃やあんぽ柿など果樹産品を買い込み発送する。", "stay": 40},
      {"place": "円盤餃子 満腹", "area": "福島市", "category": "FOOD", "desc": "鉄鍋で焼き上げる名物餃子を地酒と合わせる。", "stay": 45},
      {"place": "あづま総合運動公園", "area": "福島市", "category": "SIGHTSEEING", "desc": "イチョウ並木や噴水広場が美しい県営公園を散策。", "stay": 40},
    ],
  },
  {
    "keywords": ["茨城県", "水戸市", "Mito"],
    "spots": [
      {"place": "偕楽園", "area": "水戸市", "category": "SIGHTSEEING", "desc": "日本三名園の梅林と好文亭をめぐる。", "stay": 60},
      {"place": "弘道館", "area": "水戸市", "category": "SIGHTSEEING", "desc": "武士教育の拠点で水戸藩校の資料を見学。", "stay": 40},
      {"place": "常磐神社", "area": "水戸市", "category": "SIGHTSEEING", "desc": "徳川斉昭を祀る社で静かな参道を歩く。", "stay": 30},
      {"place": "千波湖", "area": "水戸市", "category": "REST", "desc": "湖畔の遊歩道と貸しボートでのんびり過ごす。", "stay": 45},
      {"place": "水戸芸術館", "area": "水戸市", "category": "OTHER", "desc": "タワー展望室と現代アート展示をハシゴ。", "stay": 55},
      {"place": "茨城県近代美術館", "area": "水戸市", "category": "OTHER", "desc": "横山大観など郷土画家の常設展を観賞。", "stay": 50},
      {"place": "水戸東照宮", "area": "水戸市", "category": "SIGHTSEEING", "desc": "緑に囲まれた社で勝運祈願を行う。", "stay": 30},
      {"place": "水戸南町三丁目商店街", "area": "水戸市", "category": "SHOPPING", "desc": "老舗和菓子や納豆専門店が並ぶアーケードを散策。", "stay": 40},
      {"place": "京成百貨店 水戸店", "area": "水戸市", "category": "SHOPPING", "desc": "屋上庭園を眺めつつ土産をまとめ買い。", "stay": 35},
      {"place": "水戸山翠", "area": "水戸市", "category": "FOOD", "desc": "あんこう鍋や納豆料理が味わえる郷土料理店。", "stay": 55},
    ],
  },
  {
    "keywords": ["栃木県", "宇都宮市", "Utsunomiya", "Tochigi"],
    "spots": [
      {"place": "宇都宮城址公園", "area": "宇都宮市", "category": "SIGHTSEEING", "desc": "櫓と堀が復元された城址を巡り歴史に浸る。", "stay": 40},
      {"place": "宇都宮二荒山神社", "area": "宇都宮市", "category": "SIGHTSEEING", "desc": "大鳥居から続く石段を登り市街を見渡す。", "stay": 35},
      {"place": "大谷資料館", "area": "宇都宮市", "category": "SIGHTSEEING", "desc": "巨大地下空間で採石の歴史とライトアップを体感。", "stay": 70},
      {"place": "大谷観音", "area": "宇都宮市", "category": "SIGHTSEEING", "desc": "磨崖仏と洞窟礼拝堂で荘厳な雰囲気に浸る。", "stay": 40},
      {"place": "宇都宮美術館", "area": "宇都宮市", "category": "OTHER", "desc": "森に囲まれた館で近現代美術とデザイン展を鑑賞。", "stay": 55},
      {"place": "オリオン通り商店街", "area": "宇都宮市", "category": "SHOPPING", "desc": "アーケードで餃子店とクラフトショップをはしご。", "stay": 45},
      {"place": "宇都宮餃子館", "area": "宇都宮市", "category": "FOOD", "desc": "皮や餡の違う餃子を食べ比べる人気店。", "stay": 45},
      {"place": "釜川プロムナード", "area": "宇都宮市", "category": "SIGHTSEEING", "desc": "水辺のアートとカフェが並ぶ遊歩道を散策。", "stay": 35},
      {"place": "宇都宮市文化会館", "area": "宇都宮市", "category": "OTHER", "desc": "ホールのイベントとロビー展示を鑑賞。", "stay": 40},
      {"place": "道の駅うつのみや ろまんちっく村", "area": "宇都宮市", "category": "SHOPPING", "desc": "農産物直売と温泉・ベーカリーが揃う複合施設。", "stay": 60},
    ],
  },
  {
    "keywords": ["群馬県", "前橋市", "Maebashi"],
    "spots": [
      {"place": "群馬県庁 展望ホール", "area": "前橋市", "category": "SIGHTSEEING", "desc": "地上123mの展望室で上毛三山を一望。", "stay": 35},
      {"place": "敷島公園ばら園", "area": "前橋市", "category": "SIGHTSEEING", "desc": "約600種のバラが咲く庭園を散策。", "stay": 45},
      {"place": "アーツ前橋", "area": "前橋市", "category": "OTHER", "desc": "現代アートの企画展とショップを巡る。", "stay": 50},
      {"place": "前橋東照宮", "area": "前橋市", "category": "SIGHTSEEING", "desc": "ケヤキ並木に囲まれた社で家康公を参拝。", "stay": 30},
      {"place": "グリーンドーム前橋", "area": "前橋市", "category": "OTHER", "desc": "ベロドロームで競輪イベントや展示会を見学。", "stay": 45},
      {"place": "前橋るなぱあく", "area": "前橋市", "category": "OTHER", "desc": "昭和レトロな遊具が並ぶ市営遊園地で童心に返る。", "stay": 40},
      {"place": "道の駅まえばし赤城", "area": "前橋市", "category": "SHOPPING", "desc": "赤城山麓の野菜とジェラートを味わう。", "stay": 45},
      {"place": "前橋市文化芸術れんが蔵", "area": "前橋市", "category": "OTHER", "desc": "煉瓦蔵を改装したギャラリーでライブや展示を鑑賞。", "stay": 40},
      {"place": "登利平 本店", "area": "前橋市", "category": "FOOD", "desc": "上州御用鳥めしの弁当と炭火焼きを堪能。", "stay": 45},
      {"place": "三夜沢赤城神社", "area": "前橋市", "category": "SIGHTSEEING", "desc": "深い杉林に囲まれた古社でパワースポット巡り。", "stay": 50},
    ],
  },
  {
    "keywords": ["埼玉県", "さいたま市", "Saitama", "Omiya"],
    "spots": [
      {"place": "大宮氷川神社", "area": "さいたま市", "category": "SIGHTSEEING", "desc": "2km続く参道を歩き武蔵国一宮を参拝。", "stay": 45},
      {"place": "大宮公園", "area": "さいたま市", "category": "SIGHTSEEING", "desc": "桜並木と小動物園を備えた市民の憩いを散策。", "stay": 40},
      {"place": "鉄道博物館", "area": "さいたま市", "category": "OTHER", "desc": "実物車両と運転シミュレーターで鉄道文化を体験。", "stay": 70},
      {"place": "さいたまスーパーアリーナ", "area": "さいたま市", "category": "OTHER", "desc": "イベントカレンダーを確認し音楽ライブや展示を楽しむ。", "stay": 60},
      {"place": "けやきひろば", "area": "さいたま市", "category": "REST", "desc": "植栽の広場で季節のマーケットとキッチンカーを満喫。", "stay": 35},
      {"place": "コクーンシティ", "area": "さいたま市", "category": "SHOPPING", "desc": "大型商業施設でファッションとグルメをまとめて巡る。", "stay": 60},
      {"place": "大宮盆栽美術館", "area": "さいたま市", "category": "OTHER", "desc": "貴重な盆栽コレクションと庭園を間近で鑑賞。", "stay": 50},
      {"place": "盆栽村散策路", "area": "さいたま市", "category": "SIGHTSEEING", "desc": "盆栽園が並ぶ街並みを歩き伝統技を覗きこむ。", "stay": 40},
      {"place": "宇宙劇場 プラネタリウム", "area": "さいたま市", "category": "OTHER", "desc": "最新星空プログラムでリラックス。", "stay": 45},
      {"place": "大宮市場", "area": "さいたま市", "category": "FOOD", "desc": "寿司店や食堂で海鮮丼と市場グルメを堪能。", "stay": 50},
    ],
  },
  {
    "keywords": ["千葉県", "千葉市", "Chiba"],
    "spots": [
      {"place": "千葉ポートタワー", "area": "千葉市", "category": "SIGHTSEEING", "desc": "展望スペースから東京湾と幕張新都心を一望。", "stay": 45},
      {"place": "きぼーる", "area": "千葉市", "category": "OTHER", "desc": "科学館・プラネタリウム・商業施設が一体となった複合ビル。", "stay": 60},
      {"place": "千葉市科学館", "area": "千葉市", "category": "OTHER", "desc": "体験展示を巡り最新サイエンスに触れる。", "stay": 55},
      {"place": "千葉神社", "area": "千葉市", "category": "SIGHTSEEING", "desc": "八角形の本殿が特徴的な妙見信仰の社を参拝。", "stay": 35},
      {"place": "千葉市美術館", "area": "千葉市", "category": "OTHER", "desc": "浮世絵から現代作家まで幅広い展示を鑑賞。", "stay": 50},
      {"place": "幕張メッセ", "area": "千葉市", "category": "OTHER", "desc": "大型展示場で開催されるライブやフェアを見学。", "stay": 70},
      {"place": "幕張海浜公園", "area": "千葉市", "category": "SIGHTSEEING", "desc": "海を望む芝生と日本庭園「見浜園」を散策。", "stay": 50},
      {"place": "稲毛海浜公園", "area": "千葉市", "category": "REST", "desc": "人工海浜でビーチ散歩といなげの浜のサンセットを楽しむ。", "stay": 60},
      {"place": "千葉都市モノレール", "area": "千葉市", "category": "MOVE", "desc": "懸垂式モノレールに乗り市街地の空中散走を体感。", "stay": 30},
      {"place": "千葉中央市場 食堂街", "area": "千葉市", "category": "FOOD", "desc": "市場直送の海鮮フライや寿司をリーズナブルに味わう。", "stay": 45},
    ],
  },
  {
    "keywords": ["東京都", "千代田区", "Tokyo", "Chiyoda"],
    "spots": [
      {"place": "皇居東御苑", "area": "千代田区", "category": "SIGHTSEEING", "desc": "江戸城跡の庭園と石垣を巡り都心の緑を味わう。", "stay": 50},
      {"place": "東京駅丸の内駅舎", "area": "千代田区", "category": "SIGHTSEEING", "desc": "赤レンガ駅舎とドーム天井のレリーフを鑑賞。", "stay": 30},
      {"place": "KITTE丸の内", "area": "千代田区", "category": "SHOPPING", "desc": "旧中央郵便局を再生した商業施設で限定ショップ巡り。", "stay": 45},
      {"place": "東京国際フォーラム", "area": "千代田区", "category": "OTHER", "desc": "ガラス棟の回廊とデザイン展示を見学。", "stay": 40},
      {"place": "国会議事堂参観ロビー", "area": "千代田区", "category": "SIGHTSEEING", "desc": "事前予約で本会議場と中央広間を見学。", "stay": 45},
      {"place": "日比谷公園", "area": "千代田区", "category": "SIGHTSEEING", "desc": "噴水広場と松本楼周辺で季節の花を愛でる。", "stay": 40},
      {"place": "有楽町イトシア", "area": "千代田区", "category": "SHOPPING", "desc": "駅前の複合施設でスイーツと雑貨をチェック。", "stay": 35},
      {"place": "丸の内仲通り", "area": "千代田区", "category": "SIGHTSEEING", "desc": "並木とアートが並ぶストリートでブランドショップ巡り。", "stay": 45},
      {"place": "東京シャンゼリゼビル 地下飲食街", "area": "千代田区", "category": "FOOD", "desc": "老舗洋食や立ち飲みが集まる地下街で一息。", "stay": 40},
      {"place": "丸ビル 屋上庭園", "area": "千代田区", "category": "REST", "desc": "オフィス街を望むテラスで夜景とカフェタイム。", "stay": 30},
    ],
  },
  {
    "keywords": ["神奈川県", "横浜市", "Yokohama"],
    "spots": [
      {"place": "横浜赤レンガ倉庫", "area": "横浜市", "category": "SIGHTSEEING", "desc": "歴史的倉庫で雑貨店とイベントを楽しむ。", "stay": 60},
      {"place": "山下公園", "area": "横浜市", "category": "SIGHTSEEING", "desc": "氷川丸を眺めながら海沿いの散歩道を歩く。", "stay": 45},
      {"place": "横浜中華街", "area": "横浜市", "category": "FOOD", "desc": "600店以上がひしめくグルメ街で点心食べ歩き。", "stay": 70},
      {"place": "みなとみらい21", "area": "横浜市", "category": "SIGHTSEEING", "desc": "ランドマークタワーと観覧車を背景に都市景観を撮影。", "stay": 50},
      {"place": "横浜ランドマークタワー スカイガーデン", "area": "横浜市", "category": "SIGHTSEEING", "desc": "高さ273mの展望台で港のパノラマを満喫。", "stay": 40},
      {"place": "カップヌードルミュージアム 横浜", "area": "横浜市", "category": "OTHER", "desc": "インスタントラーメン制作体験と企画展を楽しむ。", "stay": 60},
      {"place": "横浜美術館", "area": "横浜市", "category": "OTHER", "desc": "近現代アートと企画展をゆっくり鑑賞。", "stay": 55},
      {"place": "元町ショッピングストリート", "area": "横浜市", "category": "SHOPPING", "desc": "老舗ブティックとカフェが並ぶ通りを散策。", "stay": 45},
      {"place": "港の見える丘公園", "area": "横浜市", "category": "SIGHTSEEING", "desc": "ローズガーデンからベイブリッジを望む。", "stay": 35},
      {"place": "横浜ハンマーヘッド", "area": "横浜市", "category": "FOOD", "desc": "客船ターミナル直結のフードコートで港グルメを味わう。", "stay": 50},
    ],
  },
  {
    "keywords": ["新潟県", "新潟市", "Niigata"],
    "spots": [
      {"place": "萬代橋", "area": "新潟市", "category": "SIGHTSEEING", "desc": "アーチ橋を歩き信濃川の流れと街並みを撮影。", "stay": 30},
      {"place": "新潟市歴史博物館 みなとぴあ", "area": "新潟市", "category": "OTHER", "desc": "港町新潟の発展を映像と模型で学ぶ。", "stay": 55},
      {"place": "新潟せんべい王国", "area": "新潟市", "category": "OTHER", "desc": "手焼き体験で出来立ての米菓を味わう。", "stay": 50},
      {"place": "朱鷺メッセ 展望室", "area": "新潟市", "category": "SIGHTSEEING", "desc": "地上125mから佐渡島と信濃川河口を一望。", "stay": 40},
      {"place": "白山神社", "area": "新潟市", "category": "SIGHTSEEING", "desc": "庭園や能舞台を備えた総鎮守に参拝。", "stay": 35},
      {"place": "古町商店街", "area": "新潟市", "category": "SHOPPING", "desc": "老舗料亭とモダンショップが並ぶ花街跡を散策。", "stay": 45},
      {"place": "ピアBandai", "area": "新潟市", "category": "FOOD", "desc": "市場スタイルで地魚の寿司やイタリアンを味わう。", "stay": 60},
      {"place": "北方文化博物館 新潟分館", "area": "新潟市", "category": "OTHER", "desc": "豪農の館を移築した建物で文化財を鑑賞。", "stay": 45},
      {"place": "NSTゆめホール", "area": "新潟市", "category": "OTHER", "desc": "メディアタワーで最新イベントと番組展示を覗く。", "stay": 30},
      {"place": "イタリア軒", "area": "新潟市", "category": "FOOD", "desc": "老舗洋食店でタレかつ丼やボルシチを味わう。", "stay": 50},
    ],
  },
  {
    "keywords": ["富山県", "富山市", "Toyama"],
    "spots": [
      {"place": "富山城址公園", "area": "富山市", "category": "SIGHTSEEING", "desc": "堀と庭園を歩き郷土博物館で藩政史を学ぶ。", "stay": 45},
      {"place": "富岩運河環水公園", "area": "富山市", "category": "SIGHTSEEING", "desc": "天門橋展望塔から立山連峰と水辺景観を望む。", "stay": 50},
      {"place": "富山ガラス美術館", "area": "富山市", "category": "OTHER", "desc": "隈研吾建築と現代ガラス作品を鑑賞。", "stay": 55},
      {"place": "TOYAMAキラリ", "area": "富山市", "category": "OTHER", "desc": "図書館・美術館・信金が一体となる施設を回遊。", "stay": 40},
      {"place": "ますのすし本舗 源 ます寿しミュージアム", "area": "富山市", "category": "FOOD", "desc": "押し寿司作りの工程を見学し試食する。", "stay": 45},
      {"place": "富山市民プラザ", "area": "富山市", "category": "SHOPPING", "desc": "クラフトショップとカフェが入る複合施設。", "stay": 40},
      {"place": "富山県美術館", "area": "富山市", "category": "OTHER", "desc": "デザインとアートの常設展示をのんびり鑑賞。", "stay": 60},
      {"place": "総曲輪フェリオ", "area": "富山市", "category": "SHOPPING", "desc": "中心市街地の百貨店で土産や雑貨を購入。", "stay": 35},
      {"place": "薬都とやま伝承館", "area": "富山市", "category": "OTHER", "desc": "配置薬の歴史と薬箱づくりを学ぶ。", "stay": 40},
      {"place": "環水公園スターバックス", "area": "富山市", "category": "REST", "desc": "運河を望むテラスで限定ドリンクを楽しむ。", "stay": 30},
    ],
  },
  {
    "keywords": ["石川県", "金沢市", "Kanazawa"],
    "spots": [
      {"place": "兼六園", "area": "金沢市", "category": "SIGHTSEEING", "desc": "日本三名園の灯籠と池泉回遊式庭園を散策。", "stay": 60},
      {"place": "金沢城公園", "area": "金沢市", "category": "SIGHTSEEING", "desc": "復元された菱櫓や石川門を巡り城下の眺望を楽しむ。", "stay": 50},
      {"place": "ひがし茶屋街", "area": "金沢市", "category": "SIGHTSEEING", "desc": "格子戸の町家で和菓子と工芸店を巡る。", "stay": 55},
      {"place": "近江町市場", "area": "金沢市", "category": "FOOD", "desc": "海鮮丼や加賀野菜を扱う鮮魚市場で食べ歩き。", "stay": 60},
      {"place": "金沢21世紀美術館", "area": "金沢市", "category": "OTHER", "desc": "プール作品など体験型現代アートを鑑賞。", "stay": 70},
      {"place": "長町武家屋敷跡", "area": "金沢市", "category": "SIGHTSEEING", "desc": "土塀と用水が残る旧武家町でしっとり散歩。", "stay": 40},
      {"place": "尾山神社", "area": "金沢市", "category": "SIGHTSEEING", "desc": "ステンドグラスの神門を持つ前田家ゆかりの社。", "stay": 35},
      {"place": "金沢蓄音器館", "area": "金沢市", "category": "OTHER", "desc": "アンティーク蓄音機の音色を聴く実演会に参加。", "stay": 45},
      {"place": "香林坊東急スクエア", "area": "金沢市", "category": "SHOPPING", "desc": "セレクトショップとカフェを巡りお土産を探す。", "stay": 40},
      {"place": "森八 本店", "area": "金沢市", "category": "FOOD", "desc": "加賀藩御用菓子の落雁と上生菓子を喫茶で味わう。", "stay": 45},
    ],
  },
  {
    "keywords": ["福井県", "福井市", "Fukui"],
    "spots": [
      {"place": "福井城址", "area": "福井市", "category": "SIGHTSEEING", "desc": "石垣と堀が残る城跡を歩き県庁周辺を散策。", "stay": 35},
      {"place": "福井県立恐竜博物館 分館", "area": "福井市", "category": "OTHER", "desc": "恐竜の全身骨格と地質展示を鑑賞。", "stay": 60},
      {"place": "一乗谷朝倉氏遺跡資料館", "area": "福井市", "category": "OTHER", "desc": "戦国大名の城下町復元模型を学ぶ。", "stay": 50},
      {"place": "養浩館庭園", "area": "福井市", "category": "SIGHTSEEING", "desc": "水鏡に映る書院造庭園で静寂を味わう。", "stay": 40},
      {"place": "北の庄城址・柴田公園", "area": "福井市", "category": "SIGHTSEEING", "desc": "柴田勝家像と天守台跡を巡り戦国史に触れる。", "stay": 30},
      {"place": "福井市立郷土歴史博物館", "area": "福井市", "category": "OTHER", "desc": "養蚕や和紙文化を紹介する展示を見学。", "stay": 45},
      {"place": "足羽山公園", "area": "福井市", "category": "SIGHTSEEING", "desc": "桜と夜景の名所で展望台から街を一望。", "stay": 40},
      {"place": "福井駅西口 ハピリン", "area": "福井市", "category": "SHOPPING", "desc": "恐竜モニュメントを見上げながら土産を購入。", "stay": 35},
      {"place": "越前蕎麦倶楽部", "area": "福井市", "category": "FOOD", "desc": "おろしそばとソースかつ丼を味わう老舗。", "stay": 45},
      {"place": "佐佳枝廼社", "area": "福井市", "category": "SIGHTSEEING", "desc": "越前東照宮として知られる華やかな社殿を参拝。", "stay": 30},
    ],
  },
  {
    "keywords": ["山梨県", "甲府市", "Kofu"],
    "spots": [
      {"place": "甲府城跡 舞鶴城公園", "area": "甲府市", "category": "SIGHTSEEING", "desc": "天守台から富士山と甲府盆地を望む。", "stay": 45},
      {"place": "武田神社", "area": "甲府市", "category": "SIGHTSEEING", "desc": "躑躅ヶ崎館跡に立つ社で勝運御守を授かる。", "stay": 40},
      {"place": "山梨県立美術館", "area": "甲府市", "category": "OTHER", "desc": "ミレーの名画「落ち穂拾い」で知られるコレクションを鑑賞。", "stay": 55},
      {"place": "甲府駅北口よっちゃばれ広場", "area": "甲府市", "category": "REST", "desc": "噴水とスツールの並ぶ広場で休憩。", "stay": 30},
      {"place": "甲州夢小路", "area": "甲府市", "category": "SHOPPING", "desc": "レトロな路地に並ぶ雑貨店とワイナリーを巡る。", "stay": 45},
      {"place": "岡島百貨店", "area": "甲府市", "category": "SHOPPING", "desc": "老舗百貨店で宝石や銘菓をチェック。", "stay": 35},
      {"place": "昇仙峡ロープウェイ 仙娥滝駅", "area": "甲府市", "category": "SIGHTSEEING", "desc": "花崗岩の渓谷を俯瞰する空中散歩を楽しむ。", "stay": 60},
      {"place": "ワイン資料館", "area": "甲府市", "category": "OTHER", "desc": "甲州ワインの醸造道具と試飲コーナーを体験。", "stay": 45},
      {"place": "小作 甲府北口店", "area": "甲府市", "category": "FOOD", "desc": "かぼちゃほうとうと季節の小鉢で体を温める。", "stay": 50},
      {"place": "湯村温泉", "area": "甲府市", "category": "REST", "desc": "信玄公ゆかりの湯でゆったりと湯治気分。", "stay": 60},
    ],
  },
  {
    "keywords": ["長野県", "長野市", "Nagano"],
    "spots": [
      {"place": "善光寺", "area": "長野市", "category": "SIGHTSEEING", "desc": "国宝の本堂でお戒壇巡りと御朱印を体験。", "stay": 60},
      {"place": "長野県信濃美術館 東山魁夷館", "area": "長野市", "category": "OTHER", "desc": "青い風景画で知られる作家の世界に浸る。", "stay": 55},
      {"place": "善光寺仲見世通り", "area": "長野市", "category": "SHOPPING", "desc": "七味唐辛子やおやきの店をはしご。", "stay": 45},
      {"place": "城山公園", "area": "長野市", "category": "SIGHTSEEING", "desc": "桜と紅葉の名所で茶室「城山亭」を訪れる。", "stay": 40},
      {"place": "戸隠そば博物館 とんくるりん", "area": "長野市", "category": "OTHER", "desc": "手打ち体験で蕎麦の香りを存分に味わう。", "stay": 50},
      {"place": "長野市立博物館", "area": "長野市", "category": "OTHER", "desc": "善光寺平の自然と歴史を紹介する展示を見る。", "stay": 45},
      {"place": "長野えびす講煙火大会資料館", "area": "長野市", "category": "OTHER", "desc": "大花火の歴史を映像で学ぶ。", "stay": 30},
      {"place": "信州善光寺門前 みそソフト店", "area": "長野市", "category": "FOOD", "desc": "味噌ソフトやおやきなど門前グルメを堪能。", "stay": 35},
      {"place": "長野県庁 展望ロビー", "area": "長野市", "category": "SIGHTSEEING", "desc": "北アルプスと市街地を一望する無料展望。", "stay": 30},
      {"place": "善光寺表参道イルミネーション", "area": "長野市", "category": "SIGHTSEEING", "desc": "冬季にはイルミに彩られる参道を散策。", "stay": 35},
    ],
  },
  {
    "keywords": ["岐阜県", "岐阜市", "Gifu"],
    "spots": [
      {"place": "岐阜城", "area": "岐阜市", "category": "SIGHTSEEING", "desc": "金華山頂の天守から長良川流域を一望。", "stay": 60},
      {"place": "長良川鵜飼ミュージアム", "area": "岐阜市", "category": "OTHER", "desc": "鵜飼文化の仕組みや道具を学ぶ。", "stay": 50},
      {"place": "川原町和傘館", "area": "岐阜市", "category": "SIGHTSEEING", "desc": "町家が連なる古い町並みで和傘を鑑賞。", "stay": 40},
      {"place": "岐阜大仏 正法寺", "area": "岐阜市", "category": "SIGHTSEEING", "desc": "木心乾漆の巨大大仏を拝観。", "stay": 35},
      {"place": "柳ヶ瀬商店街", "area": "岐阜市", "category": "SHOPPING", "desc": "再開発が進むアーケードでカフェと雑貨を巡る。", "stay": 45},
      {"place": "岐阜シティ・タワー43", "area": "岐阜市", "category": "SIGHTSEEING", "desc": "無料展望室から夜景と濃尾平野を眺める。", "stay": 30},
      {"place": "岐阜市歴史博物館", "area": "岐阜市", "category": "OTHER", "desc": "織田信長と岐阜城下の歴史を学ぶ。", "stay": 50},
      {"place": "金華山ロープウェー山麓駅", "area": "岐阜市", "category": "MOVE", "desc": "山頂へ向かうロープウェーで空中散歩。", "stay": 30},
      {"place": "十八楼 川原町店", "area": "岐阜市", "category": "FOOD", "desc": "鮎料理と飛騨牛が評判の料理旅館で昼食。", "stay": 55},
      {"place": "みんなの森 ぎふメディアコスモス", "area": "岐阜市", "category": "OTHER", "desc": "有機的な屋根が印象的な図書館で読書時間を過ごす。", "stay": 45},
    ],
  },
  {
    "keywords": ["静岡県", "静岡市", "Shizuoka"],
    "spots": [
      {"place": "駿府城公園", "area": "静岡市", "category": "SIGHTSEEING", "desc": "徳川家康ゆかりの城跡で巽櫓と紅葉山庭園を巡る。", "stay": 50},
      {"place": "静岡県庁 展望ロビー", "area": "静岡市", "category": "SIGHTSEEING", "desc": "富士山と駿河湾を望む地上21階の展望。", "stay": 30},
      {"place": "静岡浅間神社", "area": "静岡市", "category": "SIGHTSEEING", "desc": "色鮮やかな社殿で祭囃子の歴史を感じる。", "stay": 40},
      {"place": "静岡市美術館", "area": "静岡市", "category": "OTHER", "desc": "駅直結の現代アート展示を気軽に鑑賞。", "stay": 45},
      {"place": "駿府博物館", "area": "静岡市", "category": "OTHER", "desc": "徳川期の刀剣や甲冑コレクションを鑑賞。", "stay": 40},
      {"place": "青葉シンボルロード", "area": "静岡市", "category": "SIGHTSEEING", "desc": "ケヤキ並木とストリートフードが並ぶ空間を散策。", "stay": 35},
      {"place": "静岡おでん街 おがわ", "area": "静岡市", "category": "FOOD", "desc": "黒はんぺん入りのおでんと地酒を味わう。", "stay": 45},
      {"place": "静岡PARCO", "area": "静岡市", "category": "SHOPPING", "desc": "セレクトショップでローカルブランドを探す。", "stay": 40},
      {"place": "日本平夢テラス", "area": "静岡市", "category": "SIGHTSEEING", "desc": "木組みの展望回廊から富士山と駿河湾を一望。", "stay": 60},
      {"place": "久能山東照宮ロープウェイ", "area": "静岡市", "category": "MOVE", "desc": "絶景の海岸線を眺めながら山上の社へ向かう。", "stay": 35},
    ],
  },
  {
    "keywords": ["愛知県", "名古屋市", "Nagoya"],
    "spots": [
      {"place": "名古屋城", "area": "名古屋市", "category": "SIGHTSEEING", "desc": "金鯱で知られる天守と本丸御殿を見学。", "stay": 60},
      {"place": "徳川美術館", "area": "名古屋市", "category": "OTHER", "desc": "尾張徳川家伝来の刀剣と雛道具を鑑賞。", "stay": 55},
      {"place": "オアシス21", "area": "名古屋市", "category": "SIGHTSEEING", "desc": "水の宇宙船デッキを歩き夜景を楽しむ。", "stay": 40},
      {"place": "名古屋市科学館", "area": "名古屋市", "category": "OTHER", "desc": "世界最大級のプラネタリウムで星空ショーを観賞。", "stay": 70},
      {"place": "栄地下街", "area": "名古屋市", "category": "SHOPPING", "desc": "巨大地下街で名古屋メシと雑貨を巡る。", "stay": 50},
      {"place": "熱田神宮", "area": "名古屋市", "category": "SIGHTSEEING", "desc": "三種の神器ゆかりの杜を参拝。", "stay": 45},
      {"place": "大須商店街", "area": "名古屋市", "category": "SHOPPING", "desc": "アニメ店と古着店、食べ歩きが混在する街を散策。", "stay": 60},
      {"place": "リニア・鉄道館", "area": "名古屋市", "category": "OTHER", "desc": "新幹線から在来線まで39両の実物車両を見学。", "stay": 65},
      {"place": "矢場とん 矢場町本店", "area": "名古屋市", "category": "FOOD", "desc": "味噌かつの元祖店でボリューム満点のランチ。", "stay": 45},
      {"place": "ノリタケの森", "area": "名古屋市", "category": "OTHER", "desc": "陶磁器ミュージアムと庭園で産業遺産を体感。", "stay": 50},
    ],
  },
  {
    "keywords": ["三重県", "伊勢市", "Ise"],
    "spots": [
      {"place": "伊勢神宮 内宮", "area": "伊勢市", "category": "SIGHTSEEING", "desc": "五十鈴川にかかる宇治橋を渡り正宮を参拝。", "stay": 70},
      {"place": "おはらい町", "area": "伊勢市", "category": "SHOPPING", "desc": "江戸風情の通りで土産と食べ歩きを満喫。", "stay": 55},
      {"place": "おかげ横丁", "area": "伊勢市", "category": "SHOPPING", "desc": "赤福本店や伊勢うどん店が並ぶ観光横丁。", "stay": 60},
      {"place": "猿田彦神社", "area": "伊勢市", "category": "SIGHTSEEING", "desc": "みちびきの神に旅の安全を祈る。", "stay": 30},
      {"place": "月讀宮", "area": "伊勢市", "category": "SIGHTSEEING", "desc": "静寂に包まれた別宮で心を整える。", "stay": 35},
      {"place": "二見興玉神社", "area": "伊勢市", "category": "SIGHTSEEING", "desc": "夫婦岩越しに朝日を臨む海辺の社。", "stay": 40},
      {"place": "伊勢シーパラダイス", "area": "伊勢市", "category": "OTHER", "desc": "セイウチとの触れ合いが人気の水族館。", "stay": 60},
      {"place": "伊勢河崎商人館", "area": "伊勢市", "category": "OTHER", "desc": "蔵と町家が連なる江戸期の商家を見学。", "stay": 45},
      {"place": "伊勢うどん ちとせ", "area": "伊勢市", "category": "FOOD", "desc": "もっちり麺に濃厚たれを絡める老舗の味。", "stay": 40},
      {"place": "勢乃國屋 本店", "area": "伊勢市", "category": "SHOPPING", "desc": "神代餅や神話モチーフの土産を購入。", "stay": 35},
    ],
  },
  {
    "keywords": ["滋賀県", "大津市", "Otsu"],
    "spots": [
      {"place": "琵琶湖疎水船", "area": "大津市", "category": "MOVE", "desc": "明治の水路を巡る観光船で京都方面への運航を体験。", "stay": 60},
      {"place": "三井寺", "area": "大津市", "category": "SIGHTSEEING", "desc": "国宝の仏像と琵琶湖を望む境内を散策。", "stay": 50},
      {"place": "石山寺", "area": "大津市", "category": "SIGHTSEEING", "desc": "紫式部ゆかりの寺で多宝塔や奇岩を巡る。", "stay": 55},
      {"place": "びわ湖テラス", "area": "大津市", "category": "SIGHTSEEING", "desc": "ロープウェーで登りガラス張りのデッキから大パノラマ。", "stay": 70},
      {"place": "大津港", "area": "大津市", "category": "SIGHTSEEING", "desc": "ミシガンクルーズの発着や噴水ショーを楽しむ。", "stay": 40},
      {"place": "なぎさ公園", "area": "大津市", "category": "REST", "desc": "湖畔芝生でのんびりピクニック。", "stay": 35},
      {"place": "大津市歴史博物館", "area": "大津市", "category": "OTHER", "desc": "湖都・大津の歴史と仏教文化を学ぶ。", "stay": 45},
      {"place": "浜大津アーカス", "area": "大津市", "category": "SHOPPING", "desc": "映画館とレストランが集まる複合施設で休憩。", "stay": 40},
      {"place": "近江牛レストラン ティファニー", "area": "大津市", "category": "FOOD", "desc": "ステーキやしゃぶしゃぶで近江牛を堪能。", "stay": 60},
      {"place": "皇子山運動公園展望台", "area": "大津市", "category": "SIGHTSEEING", "desc": "琵琶湖と比叡山を同時に見渡すビュースポット。", "stay": 30},
    ],
  },
  {
    "keywords": ["京都府", "京都市", "Kyoto"],
    "spots": [
      {"place": "清水寺", "area": "京都市", "category": "SIGHTSEEING", "desc": "舞台から京都市街を見下ろし国宝建築を巡る。", "stay": 70},
      {"place": "祇園花見小路", "area": "京都市", "category": "SIGHTSEEING", "desc": "町家が並ぶ石畳で茶屋文化を感じる。", "stay": 50},
      {"place": "八坂神社", "area": "京都市", "category": "SIGHTSEEING", "desc": "祇園祭の中心となる社で参拝。", "stay": 35},
      {"place": "二年坂・三年坂", "area": "京都市", "category": "SHOPPING", "desc": "京雑貨と甘味処が続く坂道を散策。", "stay": 45},
      {"place": "高台寺", "area": "京都市", "category": "SIGHTSEEING", "desc": "ライトアップで知られる庭園と方丈を巡る。", "stay": 50},
      {"place": "錦市場", "area": "京都市", "category": "FOOD", "desc": "京漬物やだし巻き卵を食べ歩く台所。", "stay": 45},
      {"place": "京都国立博物館", "area": "京都市", "category": "OTHER", "desc": "国宝級の仏像や書画をじっくり鑑賞。", "stay": 70},
      {"place": "京都駅ビル 空中経路", "area": "京都市", "category": "SIGHTSEEING", "desc": "大階段とスカイウエイを歩き夜景を堪能。", "stay": 35},
      {"place": "伊右衛門サロン アトリエ京都", "area": "京都市", "category": "FOOD", "desc": "茶寮スタイルで抹茶スイーツと軽食を楽しむ。", "stay": 45},
      {"place": "京都市京セラ美術館", "area": "京都市", "category": "OTHER", "desc": "アールデコ建築の館内でモダンアートに触れる。", "stay": 55},
    ],
  },
  {
    "keywords": ["大阪府", "大阪市", "Osaka"],
    "spots": [
      {"place": "大阪城天守閣", "area": "大阪市", "category": "SIGHTSEEING", "desc": "歴史展示と展望フロアで大坂夏の陣を学ぶ。", "stay": 60},
      {"place": "道頓堀", "area": "大阪市", "category": "FOOD", "desc": "グリコ看板の下で粉もんグルメを食べ歩き。", "stay": 55},
      {"place": "通天閣", "area": "大阪市", "category": "SIGHTSEEING", "desc": "ビリケン像に触れながら新世界の景色を眺める。", "stay": 40},
      {"place": "黒門市場", "area": "大阪市", "category": "FOOD", "desc": "フグや寿司、果物を小分けで味わう。", "stay": 45},
      {"place": "梅田スカイビル 空中庭園", "area": "大阪市", "category": "SIGHTSEEING", "desc": "360度ルーフトップで梅田の夜景を堪能。", "stay": 50},
      {"place": "中之島美術館", "area": "大阪市", "category": "OTHER", "desc": "モダンアートとデザインコレクションを鑑賞。", "stay": 55},
      {"place": "なんばパークス", "area": "大阪市", "category": "SHOPPING", "desc": "屋上庭園を散歩しながらショッピング。", "stay": 45},
      {"place": "天神橋筋商店街", "area": "大阪市", "category": "SHOPPING", "desc": "全長2.6kmのアーケードを歩き食べ歩き。", "stay": 60},
      {"place": "中央公会堂", "area": "大阪市", "category": "SIGHTSEEING", "desc": "大正建築の館内ツアーに参加。", "stay": 35},
      {"place": "551蓬莱 本店", "area": "大阪市", "category": "FOOD", "desc": "豚まんと焼売をできたてで味わう。", "stay": 30},
    ],
  },
  {
    "keywords": ["兵庫県", "神戸市", "Kobe"],
    "spots": [
      {"place": "神戸ハーバーランド", "area": "神戸市", "category": "SIGHTSEEING", "desc": "海沿いのショッピングモールと夜景を巡る。", "stay": 60},
      {"place": "メリケンパーク", "area": "神戸市", "category": "SIGHTSEEING", "desc": "神戸ポートタワーとBE KOBEモニュメントで記念撮影。", "stay": 45},
      {"place": "北野異人館街", "area": "神戸市", "category": "SIGHTSEEING", "desc": "異国情緒漂う洋館をはしご。", "stay": 55},
      {"place": "神戸布引ハーブ園", "area": "神戸市", "category": "SIGHTSEEING", "desc": "ロープウェーで上がり花畑と足湯テラスを満喫。", "stay": 70},
      {"place": "南京町", "area": "神戸市", "category": "FOOD", "desc": "中華街で小籠包や豚まんを食べ歩く。", "stay": 50},
      {"place": "生田神社", "area": "神戸市", "category": "SIGHTSEEING", "desc": "縁結びで知られる社で参拝。", "stay": 30},
      {"place": "神戸市立博物館", "area": "神戸市", "category": "OTHER", "desc": "南蛮屏風や近代美術を鑑賞。", "stay": 55},
      {"place": "旧居留地38番館", "area": "神戸市", "category": "SHOPPING", "desc": "クラシック建築でブランドショッピング。", "stay": 40},
      {"place": "サッポロ生ビール黒ラベル 神戸三宮麦酒", "area": "神戸市", "category": "FOOD", "desc": "地元野菜とクラフトビールを味わう。", "stay": 45},
      {"place": "東遊園地", "area": "神戸市", "category": "REST", "desc": "ルミナリエ会場としても有名な公園で一息。", "stay": 35},
    ],
  },
  {
    "keywords": ["奈良県", "奈良市", "Nara"],
    "spots": [
      {"place": "東大寺", "area": "奈良市", "category": "SIGHTSEEING", "desc": "世界最大級の木造建築で大仏殿を拝観。", "stay": 70},
      {"place": "奈良公園", "area": "奈良市", "category": "SIGHTSEEING", "desc": "鹿と触れ合いながら若草山周辺を散策。", "stay": 60},
      {"place": "春日大社", "area": "奈良市", "category": "SIGHTSEEING", "desc": "朱塗りの社殿と万灯籠をめぐる。", "stay": 50},
      {"place": "興福寺 国宝館", "area": "奈良市", "category": "OTHER", "desc": "阿修羅像など奈良仏教の名品を鑑賞。", "stay": 55},
      {"place": "ならまち格子の家", "area": "奈良市", "category": "SIGHTSEEING", "desc": "町家を再現した施設で暮らしの歴史に触れる。", "stay": 40},
      {"place": "ならまち工房", "area": "奈良市", "category": "SHOPPING", "desc": "クラフト作家の工房を巡り手仕事体験。", "stay": 45},
      {"place": "奈良県立美術館", "area": "奈良市", "category": "OTHER", "desc": "仏教美術と近現代作品をゆっくり鑑賞。", "stay": 45},
      {"place": "中谷堂", "area": "奈良市", "category": "FOOD", "desc": "高速餅つきで話題のよもぎ餅を出来たてで味わう。", "stay": 30},
      {"place": "東向商店街", "area": "奈良市", "category": "SHOPPING", "desc": "土産店とカフェが並ぶアーケードを散策。", "stay": 35},
      {"place": "猿沢池", "area": "奈良市", "category": "REST", "desc": "池畔に腰掛けて五重塔の水鏡を眺める。", "stay": 25},
    ],
  },
  {
    "keywords": ["和歌山県", "和歌山市", "Wakayama"],
    "spots": [
      {"place": "和歌山城", "area": "和歌山市", "category": "SIGHTSEEING", "desc": "天守から紀ノ川と紀伊水道を望む。", "stay": 50},
      {"place": "和歌山公園動物園", "area": "和歌山市", "category": "OTHER", "desc": "城内の小さな動物園でリスザルやツキノワグマを見る。", "stay": 40},
      {"place": "紀州東照宮", "area": "和歌山市", "category": "SIGHTSEEING", "desc": "権現造の社殿と急な石段を登り絶景を堪能。", "stay": 45},
      {"place": "和歌浦天満宮", "area": "和歌山市", "category": "SIGHTSEEING", "desc": "極彩色の社殿から和歌浦湾を見渡す。", "stay": 35},
      {"place": "友ヶ島汽船 加太港", "area": "和歌山市", "category": "MOVE", "desc": "要塞跡で人気の友ヶ島クルーズに乗船。", "stay": 60},
      {"place": "黒潮市場", "area": "和歌山市", "category": "FOOD", "desc": "マグロ解体ショーと海鮮バーベキューを満喫。", "stay": 55},
      {"place": "ポルトヨーロッパ", "area": "和歌山市", "category": "SIGHTSEEING", "desc": "地中海風テーマパークでアトラクションを楽しむ。", "stay": 60},
      {"place": "紀三井寺", "area": "和歌山市", "category": "SIGHTSEEING", "desc": "海南方面を一望できる境内で桜を鑑賞。", "stay": 40},
      {"place": "和歌山県立近代美術館", "area": "和歌山市", "category": "OTHER", "desc": "和歌浦を描いた近代絵画や彫刻に触れる。", "stay": 45},
      {"place": "山為食堂", "area": "和歌山市", "category": "FOOD", "desc": "濃厚醤油スープの和歌山ラーメンで締める。", "stay": 35},
    ],
  },
  {
    "keywords": ["鳥取県", "鳥取市", "Tottori"],
    "spots": [
      {"place": "鳥取砂丘", "area": "鳥取市", "category": "SIGHTSEEING", "desc": "砂丘リフトと砂の美術館を巡り大自然を体感。", "stay": 70},
      {"place": "砂丘センター 見晴らしの丘", "area": "鳥取市", "category": "SIGHTSEEING", "desc": "展望台から海と砂丘のコントラストを眺める。", "stay": 35},
      {"place": "仁風閣", "area": "鳥取市", "category": "SIGHTSEEING", "desc": "白亜の洋館で西洋建築と藩主の暮らしを見学。", "stay": 45},
      {"place": "鳥取城跡", "area": "鳥取市", "category": "SIGHTSEEING", "desc": "山城の石垣と久松公園の桜を散策。", "stay": 40},
      {"place": "鳥取県立博物館", "area": "鳥取市", "category": "OTHER", "desc": "因幡地方の自然史と考古資料を鑑賞。", "stay": 50},
      {"place": "わらべ館", "area": "鳥取市", "category": "OTHER", "desc": "童謡とおもちゃのミュージアムで体験展示を楽しむ。", "stay": 45},
      {"place": "鳥取港海鮮市場 かろいち", "area": "鳥取市", "category": "FOOD", "desc": "境港直送の海鮮や松葉ガニを味わう。", "stay": 55},
      {"place": "鳥取しゃんしゃん祭展示館", "area": "鳥取市", "category": "OTHER", "desc": "傘踊りの衣装と映像を見学。", "stay": 30},
      {"place": "鳥取市民会館前商店街", "area": "鳥取市", "category": "SHOPPING", "desc": "地元和菓子と工芸品を扱う商店を巡る。", "stay": 35},
      {"place": "すなば珈琲 鳥取駅前店", "area": "鳥取市", "category": "FOOD", "desc": "鳥取砂丘ラテなどご当地ドリンクで休憩。", "stay": 30},
    ],
  },
  {
    "keywords": ["島根県", "松江市", "Matsue"],
    "spots": [
      {"place": "松江城", "area": "松江市", "category": "SIGHTSEEING", "desc": "現存天守から宍道湖と城下町を眺望。", "stay": 60},
      {"place": "塩見縄手", "area": "松江市", "category": "SIGHTSEEING", "desc": "武家屋敷が残る堀沿いの街並みを散策。", "stay": 45},
      {"place": "小泉八雲旧居", "area": "松江市", "category": "SIGHTSEEING", "desc": "ラフカディオ・ハーンの暮らしぶりを知る。", "stay": 35},
      {"place": "松江堀川遊覧船", "area": "松江市", "category": "MOVE", "desc": "小舟で堀川を巡り低い橋をくぐる体験。", "stay": 50},
      {"place": "八雲立つ風土記の丘", "area": "松江市", "category": "OTHER", "desc": "古墳出土品と国引き神話を学ぶ。", "stay": 45},
      {"place": "宍道湖夕日スポット", "area": "松江市", "category": "SIGHTSEEING", "desc": "夕日スポットで湖面に映る黄金色を鑑賞。", "stay": 40},
      {"place": "カラコロ工房", "area": "松江市", "category": "SHOPPING", "desc": "レトロビルで和菓子作りやアクセサリー体験。", "stay": 50},
      {"place": "松江しんじ湖温泉 足湯", "area": "松江市", "category": "REST", "desc": "湖畔にある無料足湯で旅の疲れを癒やす。", "stay": 30},
      {"place": "一畑百貨店 松江店", "area": "松江市", "category": "SHOPPING", "desc": "出雲そばや海産物の土産を購入。", "stay": 35},
      {"place": "八雲庵", "area": "松江市", "category": "FOOD", "desc": "割子そばと鴨南蛮で地元の味を楽しむ。", "stay": 45},
    ],
  },
  {
    "keywords": ["岡山県", "岡山市", "Okayama"],
    "spots": [
      {"place": "岡山城", "area": "岡山市", "category": "SIGHTSEEING", "desc": "漆黒の天守と後楽園の景観をセットで巡る。", "stay": 60},
      {"place": "後楽園", "area": "岡山市", "category": "SIGHTSEEING", "desc": "大名庭園で茶屋と能舞台を楽しむ。", "stay": 55},
      {"place": "岡山後楽園前 日本庭園カフェ", "area": "岡山市", "category": "REST", "desc": "庭園を眺めながら抹茶スイーツを味わう。", "stay": 35},
      {"place": "林原美術館", "area": "岡山市", "category": "OTHER", "desc": "刀剣や茶道具を収蔵する私設美術館を鑑賞。", "stay": 45},
      {"place": "岡山県立美術館", "area": "岡山市", "category": "OTHER", "desc": "備前焼や近代洋画のコレクションを観る。", "stay": 50},
      {"place": "表町商店街", "area": "岡山市", "category": "SHOPPING", "desc": "アーケードで桃スイーツと雑貨を物色。", "stay": 45},
      {"place": "岡山シティミュージアム", "area": "岡山市", "category": "OTHER", "desc": "城下町の歴史やデニム文化を学ぶ。", "stay": 40},
      {"place": "さんすて岡山", "area": "岡山市", "category": "SHOPPING", "desc": "駅ナカ商業施設でフルーツ土産を購入。", "stay": 35},
      {"place": "くらしきシーサイド温泉 ゆらら岡山", "area": "岡山市", "category": "REST", "desc": "天然温泉と岩盤浴でリラックス。", "stay": 60},
      {"place": "味司 野村", "area": "岡山市", "category": "FOOD", "desc": "デミカツ丼発祥の店で名物ランチを堪能。", "stay": 45},
    ],
  },
  {
    "keywords": ["広島県", "広島市", "Hiroshima"],
    "spots": [
      {"place": "原爆ドーム", "area": "広島市", "category": "SIGHTSEEING", "desc": "負の遺産を前に平和への祈りを新たにする。", "stay": 40},
      {"place": "広島平和記念資料館", "area": "広島市", "category": "OTHER", "desc": "被爆資料と証言を通じて歴史を学ぶ。", "stay": 70},
      {"place": "平和記念公園", "area": "広島市", "category": "SIGHTSEEING", "desc": "慰霊碑と慰霊堂を巡り静かな時間を過ごす。", "stay": 50},
      {"place": "広島城", "area": "広島市", "category": "SIGHTSEEING", "desc": "復元天守で毛利・福島期の城下町史を学ぶ。", "stay": 45},
      {"place": "おりづるタワー", "area": "広島市", "category": "SIGHTSEEING", "desc": "屋上デッキから市街地と瀬戸内海を一望。", "stay": 40},
      {"place": "広島市現代美術館", "area": "広島市", "category": "OTHER", "desc": "戦後美術と地域作家の作品を鑑賞。", "stay": 55},
      {"place": "ひろしま美術館", "area": "広島市", "category": "OTHER", "desc": "印象派コレクションと日本画を楽しむ。", "stay": 45},
      {"place": "お好み村", "area": "広島市", "category": "FOOD", "desc": "複数の鉄板店で本場のお好み焼きを食べ比べ。", "stay": 60},
      {"place": "本通商店街", "area": "広島市", "category": "SHOPPING", "desc": "アーケードで土産とファッションを探索。", "stay": 50},
      {"place": "縮景園", "area": "広島市", "category": "SIGHTSEEING", "desc": "回遊式庭園で四季の景を楽しむ。", "stay": 45},
    ],
  },
  {
    "keywords": ["山口県", "下関市", "Shimonoseki"],
    "spots": [
      {"place": "唐戸市場", "area": "下関市", "category": "FOOD", "desc": "昼の寿司バトルで旬のフグや海鮮丼を堪能。", "stay": 60},
      {"place": "海峡ゆめタワー", "area": "下関市", "category": "SIGHTSEEING", "desc": "高さ153mの展望から関門海峡の絶景を眺める。", "stay": 40},
      {"place": "赤間神宮", "area": "下関市", "category": "SIGHTSEEING", "desc": "壇ノ浦合戦ゆかりの竜宮造り社殿を参拝。", "stay": 35},
      {"place": "カモンワーフ", "area": "下関市", "category": "SHOPPING", "desc": "海沿いの商業施設で海産物とスイーツを購入。", "stay": 45},
      {"place": "関門海峡ミュージアム", "area": "下関市", "category": "OTHER", "desc": "海峡の歴史や船の操船シミュレーターを体験。", "stay": 50},
      {"place": "みもすそ川公園", "area": "下関市", "category": "SIGHTSEEING", "desc": "長州砲レプリカと壇ノ浦古戦場の景色を望む。", "stay": 30},
      {"place": "下関市立しものせき水族館 海響館", "area": "下関市", "category": "OTHER", "desc": "国内最大級のフグ展示とペンギン村を楽しむ。", "stay": 70},
      {"place": "旧下関英国領事館", "area": "下関市", "category": "SIGHTSEEING", "desc": "明治期レンガ建築で国際貿易の歴史を知る。", "stay": 40},
      {"place": "火の山公園", "area": "下関市", "category": "SIGHTSEEING", "desc": "ロープウェーで山頂に上り関門橋の夜景を鑑賞。", "stay": 50},
      {"place": "下関南部町郵便局", "area": "下関市", "category": "SHOPPING", "desc": "近代建築の郵便局でご当地スタンプや記念品を入手。", "stay": 25},
    ],
  },
  {
    "keywords": ["徳島県", "徳島市", "Tokushima"],
    "spots": [
      {"place": "眉山ロープウェイ", "area": "徳島市", "category": "MOVE", "desc": "山頂から吉野川と市街地を一望。", "stay": 45},
      {"place": "阿波おどり会館", "area": "徳島市", "category": "OTHER", "desc": "毎日開催の踊り公演と資料展示を楽しむ。", "stay": 60},
      {"place": "徳島中央公園", "area": "徳島市", "category": "SIGHTSEEING", "desc": "徳島城跡の庭園と石垣を散策。", "stay": 40},
      {"place": "ポッポ街商店街", "area": "徳島市", "category": "SHOPPING", "desc": "同人ショップやアニメグッズが集まる商店街を巡る。", "stay": 35},
      {"place": "徳島県立近代美術館", "area": "徳島市", "category": "OTHER", "desc": "パウル・クレーなど国内屈指のコレクションを鑑賞。", "stay": 50},
      {"place": "新町川ボードウォーク", "area": "徳島市", "category": "SIGHTSEEING", "desc": "屋台船やカフェが並ぶ水辺を散歩。", "stay": 40},
      {"place": "ひょうたん島クルーズ", "area": "徳島市", "category": "MOVE", "desc": "市内河川を30分で巡る無料遊覧船を楽しむ。", "stay": 30},
      {"place": "徳島ラーメン 東大 本店", "area": "徳島市", "category": "FOOD", "desc": "甘辛豚骨スープに生卵を落として味わう。", "stay": 35},
      {"place": "蔵本公園", "area": "徳島市", "category": "SIGHTSEEING", "desc": "桜と紅葉の名所で静かな散策。", "stay": 30},
      {"place": "とくしま藍あそび", "area": "徳島市", "category": "OTHER", "desc": "伝統藍染の体験工房でストールを染める。", "stay": 60},
    ],
  },
  {
    "keywords": ["香川県", "高松市", "Takamatsu"],
    "spots": [
      {"place": "栗林公園", "area": "高松市", "category": "SIGHTSEEING", "desc": "四国地方の特別名勝で池泉回遊式庭園を散策。", "stay": 60},
      {"place": "高松城跡 玉藻公園", "area": "高松市", "category": "SIGHTSEEING", "desc": "海水を引き込む堀を舟で巡り披雲閣を見学。", "stay": 50},
      {"place": "北浜alley", "area": "高松市", "category": "SHOPPING", "desc": "倉庫群をリノベしたカフェと雑貨店を巡る。", "stay": 45},
      {"place": "高松シンボルタワー", "area": "高松市", "category": "SIGHTSEEING", "desc": "展望フロアから瀬戸内海と屋島を望む。", "stay": 40},
      {"place": "屋島山上", "area": "高松市", "category": "SIGHTSEEING", "desc": "源平合戦の古戦場を俯瞰する展望地を歩く。", "stay": 55},
      {"place": "高松丸亀町商店街", "area": "高松市", "category": "SHOPPING", "desc": "ガラス屋根アーケードで四国最大級の買い物体験。", "stay": 50},
      {"place": "香川県立ミュージアム", "area": "高松市", "category": "OTHER", "desc": "讃岐漆器や古文書に触れる常設展。", "stay": 45},
      {"place": "瓦町FLAG", "area": "高松市", "category": "SHOPPING", "desc": "駅ビルでローカルファッションとグルメを巡る。", "stay": 35},
      {"place": "うどんバカ一代", "area": "高松市", "category": "FOOD", "desc": "釜バターうどんが名物の人気店。", "stay": 35},
      {"place": "ことでんことでんミュージアム", "area": "高松市", "category": "OTHER", "desc": "私鉄の歴史展示と旧車両見学で鉄道文化を知る。", "stay": 40},
    ],
  },
  {
    "keywords": ["愛媛県", "松山市", "Matsuyama"],
    "spots": [
      {"place": "松山城", "area": "松山市", "category": "SIGHTSEEING", "desc": "連立式天守から瀬戸内海と城下町を一望。", "stay": 60},
      {"place": "道後温泉本館", "area": "松山市", "category": "REST", "desc": "日本最古の湯で坊っちゃんの世界に浸る。", "stay": 60},
      {"place": "道後ハイカラ通り", "area": "松山市", "category": "SHOPPING", "desc": "温泉街の土産店と足湯カフェをはしご。", "stay": 45},
      {"place": "坂の上の雲ミュージアム", "area": "松山市", "category": "OTHER", "desc": "司馬遼太郎の小説世界と明治の偉人を学ぶ。", "stay": 50},
      {"place": "萬翠荘", "area": "松山市", "category": "SIGHTSEEING", "desc": "アールヌーボー様式の迎賓館を見学。", "stay": 40},
      {"place": "松山市立子規記念博物館", "area": "松山市", "category": "OTHER", "desc": "俳句と野球を愛した正岡子規の資料を鑑賞。", "stay": 45},
      {"place": "ロープウェー街", "area": "松山市", "category": "SHOPPING", "desc": "愛媛みかんスイーツや砥部焼を扱う商店街。", "stay": 40},
      {"place": "石手寺", "area": "松山市", "category": "SIGHTSEEING", "desc": "四国霊場51番札所で国宝仁王門を参拝。", "stay": 50},
      {"place": "伊予鉄道 大街道駅", "area": "松山市", "category": "MOVE", "desc": "市内電車に乗ってレトロな路面電車旅を楽しむ。", "stay": 25},
      {"place": "鍋焼きうどん アサヒ", "area": "松山市", "category": "FOOD", "desc": "甘めの出汁と半熟卵が特徴の名物鍋焼きうどん。", "stay": 35},
    ],
  },
  {
    "keywords": ["高知県", "高知市", "Kochi"],
    "spots": [
      {"place": "高知城", "area": "高知市", "category": "SIGHTSEEING", "desc": "現存天守と本丸御殿を巡り土佐の歴史を学ぶ。", "stay": 60},
      {"place": "ひろめ市場", "area": "高知市", "category": "FOOD", "desc": "カツオの藁焼きやご当地グルメを屋台形式で食べ歩き。", "stay": 55},
      {"place": "桂浜", "area": "高知市", "category": "SIGHTSEEING", "desc": "坂本龍馬像と太平洋の景観を楽しむ。", "stay": 50},
      {"place": "坂本龍馬記念館", "area": "高知市", "category": "OTHER", "desc": "龍馬の足跡と幕末資料を鑑賞。", "stay": 60},
      {"place": "高知県立美術館", "area": "高知市", "category": "OTHER", "desc": "シャガールコレクションと現代アート展を観る。", "stay": 55},
      {"place": "日曜市", "area": "高知市", "category": "SHOPPING", "desc": "1km続く朝市で野菜や民芸品を物色。", "stay": 45},
      {"place": "播磨屋橋", "area": "高知市", "category": "SIGHTSEEING", "desc": "よさこい節で知られる橋の周辺を散策。", "stay": 30},
      {"place": "高知よさこい情報交流館", "area": "高知市", "category": "OTHER", "desc": "衣装展示と実演映像で祭り文化に浸る。", "stay": 40},
      {"place": "はりまや橋商店街", "area": "高知市", "category": "SHOPPING", "desc": "土佐和紙や芋けんぴを扱う店舗を巡る。", "stay": 35},
      {"place": "明神丸 ひろめ市場店", "area": "高知市", "category": "FOOD", "desc": "炙りたて鰹のたたきを藁焼き実演付きで味わう。", "stay": 40},
    ],
  },
  {
    "keywords": ["福岡県", "福岡市", "Fukuoka"],
    "spots": [
      {"place": "福岡タワー", "area": "福岡市", "category": "SIGHTSEEING", "desc": "海浜タワーの展望室からシーサイドももちを一望。", "stay": 45},
      {"place": "大濠公園", "area": "福岡市", "category": "SIGHTSEEING", "desc": "ボート遊びとスタバでのんびり湖畔時間。", "stay": 50},
      {"place": "福岡市美術館", "area": "福岡市", "category": "OTHER", "desc": "ミロや草間彌生作品、アジア美術の常設を鑑賞。", "stay": 55},
      {"place": "博多祇園山笠 博多町屋ふるさと館", "area": "福岡市", "category": "OTHER", "desc": "祭りの歴史や飾り山を間近で見る。", "stay": 45},
      {"place": "キャナルシティ博多", "area": "福岡市", "category": "SHOPPING", "desc": "噴水ショーとブランドショップを巡る大型施設。", "stay": 60},
      {"place": "中洲屋台街", "area": "福岡市", "category": "FOOD", "desc": "屋台で豚骨ラーメンや焼きラーメンを堪能。", "stay": 55},
      {"place": "櫛田神社", "area": "福岡市", "category": "SIGHTSEEING", "desc": "山笠を奉納する社で巨大飾り山を鑑賞。", "stay": 35},
      {"place": "博多駅デイトス", "area": "福岡市", "category": "SHOPPING", "desc": "駅ナカで明太子や銘菓を購入。", "stay": 40},
      {"place": "博多ポートタワー", "area": "福岡市", "category": "SIGHTSEEING", "desc": "無料展望台から博多湾を眺望。", "stay": 30},
      {"place": "元祖長浜屋", "area": "福岡市", "category": "FOOD", "desc": "替え玉発祥の店であっさり豚骨を味わう。", "stay": 35},
    ],
  },
  {
    "keywords": ["佐賀県", "佐賀市", "Saga"],
    "spots": [
      {"place": "佐賀城本丸歴史館", "area": "佐賀市", "category": "OTHER", "desc": "日本最大級の木造復元施設で幕末の科学技術を学ぶ。", "stay": 60},
      {"place": "佐賀城公園", "area": "佐賀市", "category": "SIGHTSEEING", "desc": "堀と芝生広場を散策しライトアップも楽しむ。", "stay": 40},
      {"place": "佐賀県立美術館", "area": "佐賀市", "category": "OTHER", "desc": "鍋島焼や岡田三郎助の作品を鑑賞。", "stay": 45},
      {"place": "佐賀県立博物館", "area": "佐賀市", "category": "OTHER", "desc": "吉野ヶ里遺跡やバルーンフェスタ資料を学ぶ。", "stay": 50},
      {"place": "呉服元町商店街", "area": "佐賀市", "category": "SHOPPING", "desc": "レトロなアーケードでカフェと雑貨を巡る。", "stay": 45},
      {"place": "佐賀バルーンミュージアム", "area": "佐賀市", "category": "OTHER", "desc": "熱気球の操縦シミュレーターを体験。", "stay": 40},
      {"place": "与賀神社", "area": "佐賀市", "category": "SIGHTSEEING", "desc": "クスの巨木が並ぶ境内で田植え祭を紹介。", "stay": 35},
      {"place": "サガハツ", "area": "佐賀市", "category": "SHOPPING", "desc": "JR佐賀駅の新商業施設で土産探し。", "stay": 35},
      {"place": "東与賀海岸シチメンソウ群生地", "area": "佐賀市", "category": "SIGHTSEEING", "desc": "秋に紅く染まる塩生植物の群生を鑑賞。", "stay": 45},
      {"place": "井出ちゃんぽん", "area": "佐賀市", "category": "FOOD", "desc": "具沢山の白濁スープを大盛りで楽しむ。", "stay": 40},
    ],
  },
  {
    "keywords": ["長崎県", "長崎市", "Nagasaki"],
    "spots": [
      {"place": "グラバー園", "area": "長崎市", "category": "SIGHTSEEING", "desc": "洋館群と長崎港を見下ろす丘を散策。", "stay": 60},
      {"place": "大浦天主堂", "area": "長崎市", "category": "SIGHTSEEING", "desc": "世界遺産の教会でステンドグラスを鑑賞。", "stay": 40},
      {"place": "長崎新地中華街", "area": "長崎市", "category": "FOOD", "desc": "ちゃんぽんや角煮まんじゅうを食べ歩き。", "stay": 50},
      {"place": "出島", "area": "長崎市", "category": "SIGHTSEEING", "desc": "復元されたオランダ商館跡で交易史を学ぶ。", "stay": 55},
      {"place": "長崎原爆資料館", "area": "長崎市", "category": "OTHER", "desc": "被爆資料と映像シアターで平和への思いを深める。", "stay": 70},
      {"place": "平和公園", "area": "長崎市", "category": "SIGHTSEEING", "desc": "平和祈念像に献花し静かに佇む。", "stay": 40},
      {"place": "稲佐山展望台", "area": "長崎市", "category": "SIGHTSEEING", "desc": "世界新三大夜景に選ばれた光景を楽しむ。", "stay": 50},
      {"place": "眼鏡橋", "area": "長崎市", "category": "SIGHTSEEING", "desc": "石造アーチと川面のリフレクションを撮影。", "stay": 30},
      {"place": "浜町アーケード", "area": "長崎市", "category": "SHOPPING", "desc": "老舗カステラ店や雑貨屋を巡るアーケード街。", "stay": 45},
      {"place": "四海樓", "area": "長崎市", "category": "FOOD", "desc": "ちゃんぽん発祥の店で本場の味を堪能。", "stay": 45},
    ],
  },
  {
    "keywords": ["熊本県", "熊本市", "Kumamoto"],
    "spots": [
      {"place": "熊本城", "area": "熊本市", "category": "SIGHTSEEING", "desc": "復旧が進む天守と特別公開エリアを見学。", "stay": 60},
      {"place": "加藤神社", "area": "熊本市", "category": "SIGHTSEEING", "desc": "熊本城の眺望と戦国武将の歴史に触れる。", "stay": 35},
      {"place": "城彩苑 桜の小路", "area": "熊本市", "category": "SHOPPING", "desc": "肥後銘菓や郷土料理を集めた観光施設を散策。", "stay": 45},
      {"place": "水前寺成趣園", "area": "熊本市", "category": "SIGHTSEEING", "desc": "東海道を縮景した池泉庭園を歩く。", "stay": 50},
      {"place": "熊本県立美術館", "area": "熊本市", "category": "OTHER", "desc": "細川家伝来の茶道具や西洋画を鑑賞。", "stay": 50},
      {"place": "くまモンスクエア", "area": "熊本市", "category": "OTHER", "desc": "県PRキャラのステージと限定グッズを楽しむ。", "stay": 35},
      {"place": "上通アーケード", "area": "熊本市", "category": "SHOPPING", "desc": "カフェと雑貨が並ぶアーケードをぶらり。", "stay": 45},
      {"place": "下通アーケード", "area": "熊本市", "category": "SHOPPING", "desc": "若者向けショップと飲食店が集まるエリアを散策。", "stay": 40},
      {"place": "桂花ラーメン 本店", "area": "熊本市", "category": "FOOD", "desc": "マー油香る熊本ラーメンを味わう。", "stay": 35},
      {"place": "桜の馬場 直売所", "area": "熊本市", "category": "FOOD", "desc": "馬刺しやからし蓮根を食べ歩くフードコート。", "stay": 40},
    ],
  },
  {
    "keywords": ["大分県", "別府市", "Beppu"],
    "spots": [
      {"place": "別府地獄めぐり", "area": "別府市", "category": "SIGHTSEEING", "desc": "海地獄や血の池地獄など多彩な温泉噴出口を巡る。", "stay": 70},
      {"place": "竹瓦温泉", "area": "別府市", "category": "REST", "desc": "明治創建の共同浴場で砂湯と熱湯を体験。", "stay": 45},
      {"place": "別府タワー", "area": "別府市", "category": "SIGHTSEEING", "desc": "展望室から別府湾と高崎山を眺める。", "stay": 35},
      {"place": "海浜砂湯", "area": "別府市", "category": "REST", "desc": "波音を聞きながら砂に埋もれてデトックス。", "stay": 50},
      {"place": "杉乃井ホテル アクアガーデン", "area": "別府市", "category": "OTHER", "desc": "噴水ショー付きインフィニティ温泉プールを楽しむ。", "stay": 60},
      {"place": "別府ロープウェイ", "area": "別府市", "category": "MOVE", "desc": "鶴見岳山頂まで空中散歩し峰から街を一望。", "stay": 45},
      {"place": "別府北浜公園", "area": "別府市", "category": "REST", "desc": "足湯と芝生広場で湯けむり景観を楽しむ。", "stay": 35},
      {"place": "別府市竹細工伝統産業会館", "area": "別府市", "category": "OTHER", "desc": "大分県伝統工芸の竹編み技を見学し体験。", "stay": 55},
      {"place": "鉄輪温泉 ひょうたん温泉", "area": "別府市", "category": "REST", "desc": "滝湯や蒸し湯を備えたユネスコ認定温泉を堪能。", "stay": 60},
      {"place": "東洋軒", "area": "別府市", "category": "FOOD", "desc": "別府冷麺発祥の店で牛骨スープと麺を味わう。", "stay": 45},
    ],
  },
  {
    "keywords": ["宮崎県", "宮崎市", "Miyazaki"],
    "spots": [
      {"place": "青島神社", "area": "宮崎市", "category": "SIGHTSEEING", "desc": "鬼の洗濯板に囲まれた島の社で南国ムードを満喫。", "stay": 60},
      {"place": "堀切峠", "area": "宮崎市", "category": "SIGHTSEEING", "desc": "フェニックス並木と太平洋を望む絶景ドライブ。", "stay": 40},
      {"place": "宮崎県庁本館", "area": "宮崎市", "category": "SIGHTSEEING", "desc": "昭和モダン建築の県庁舎を見学。", "stay": 30},
      {"place": "宮崎県立美術館", "area": "宮崎市", "category": "OTHER", "desc": "郷土作家の作品と近代アートを鑑賞。", "stay": 50},
      {"place": "宮崎神宮", "area": "宮崎市", "category": "SIGHTSEEING", "desc": "巨木の参道が続く神話の社を参拝。", "stay": 45},
      {"place": "宮崎科学技術館", "area": "宮崎市", "category": "OTHER", "desc": "H-IIロケット模型とプラネタリウムを楽しむ。", "stay": 55},
      {"place": "橘通り商店街", "area": "宮崎市", "category": "SHOPPING", "desc": "百貨店やカフェが並ぶ中心街で買い物。", "stay": 40},
      {"place": "フローランテ宮崎", "area": "宮崎市", "category": "SIGHTSEEING", "desc": "花と緑のテーマパークで季節のライトアップを鑑賞。", "stay": 50},
      {"place": "おぐらのチキン南蛮", "area": "宮崎市", "category": "FOOD", "desc": "甘酢とタルタルが絶妙な名物料理を味わう。", "stay": 45},
      {"place": "AOSHIMA BEACH PARK", "area": "宮崎市", "category": "REST", "desc": "海岸沿いのカフェコンテナでサーフカルチャーに浸る。", "stay": 40},
    ],
  },
  {
    "keywords": ["鹿児島県", "鹿児島市", "Kagoshima"],
    "spots": [
      {"place": "城山公園 展望台", "area": "鹿児島市", "category": "SIGHTSEEING", "desc": "桜島と錦江湾を一望する定番展望。", "stay": 45},
      {"place": "仙巌園", "area": "鹿児島市", "category": "SIGHTSEEING", "desc": "島津家別邸で庭園と尚古集成館を見学。", "stay": 70},
      {"place": "照国神社", "area": "鹿児島市", "category": "SIGHTSEEING", "desc": "西郷隆盛を祀る社で参拝。", "stay": 30},
      {"place": "天文館むじゃき", "area": "鹿児島市", "category": "FOOD", "desc": "白くまかき氷の元祖店でスイーツを楽しむ。", "stay": 45},
      {"place": "鹿児島市維新ふるさと館", "area": "鹿児島市", "category": "OTHER", "desc": "維新の立役者や歴史を体感展示で学ぶ。", "stay": 55},
      {"place": "ドルフィンポート跡 みなと大通り", "area": "鹿児島市", "category": "SIGHTSEEING", "desc": "桜島を正面に望む海沿いの遊歩道を散策。", "stay": 35},
      {"place": "かごしま水族館", "area": "鹿児島市", "category": "OTHER", "desc": "ジンベエザメが泳ぐ大水槽やイルカタイムを観覧。", "stay": 60},
      {"place": "天文館通り", "area": "鹿児島市", "category": "SHOPPING", "desc": "アーケード街で黒豚料理やさつま揚げを探す。", "stay": 50},
      {"place": "城山ホテル鹿児島 さつま乃湯", "area": "鹿児島市", "category": "REST", "desc": "桜島を望む絶景温泉でリフレッシュ。", "stay": 60},
      {"place": "吾愛人 本店", "area": "鹿児島市", "category": "FOOD", "desc": "黒豚しゃぶしゃぶと郷土料理を味わう老舗。", "stay": 50},
    ],
  },
  {
    "keywords": ["沖縄県", "那覇市", "Okinawa", "Naha"],
    "spots": [
      {"place": "首里城公園", "area": "那覇市", "category": "SIGHTSEEING", "desc": "再建された正殿を見学し琉球王朝文化を感じる。", "stay": 60},
      {"place": "玉陵", "area": "那覇市", "category": "SIGHTSEEING", "desc": "王族の陵墓を巡り石造美術に触れる。", "stay": 35},
      {"place": "国際通り", "area": "那覇市", "category": "SHOPPING", "desc": "土産店と沖縄グルメを食べ歩くメインストリート。", "stay": 60},
      {"place": "牧志公設市場", "area": "那覇市", "category": "FOOD", "desc": "鮮魚を選んで2階食堂で調理してもらう体験。", "stay": 50},
      {"place": "波の上ビーチ", "area": "那覇市", "category": "REST", "desc": "市街地に隣接する人工ビーチで泳ぐ。", "stay": 45},
      {"place": "福州園", "area": "那覇市", "category": "SIGHTSEEING", "desc": "姉妹都市をモチーフにした中国式庭園を散策。", "stay": 40},
      {"place": "壺屋やちむん通り", "area": "那覇市", "category": "SHOPPING", "desc": "伝統陶器の工房とカフェが並ぶ通りを歩く。", "stay": 45},
      {"place": "Tギャラリア沖縄", "area": "那覇市", "category": "SHOPPING", "desc": "免税ブランドショップで買い物を楽しむ。", "stay": 50},
      {"place": "首里当蔵町 石畳道", "area": "那覇市", "category": "SIGHTSEEING", "desc": "琉球王朝時代の石畳を歩き城下町を体感。", "stay": 35},
      {"place": "ジャッキーステーキハウス", "area": "那覇市", "category": "FOOD", "desc": "アメリカンスタイルのステーキで旅の締め。", "stay": 45},
    ],
  },
]


def ts_string(value: str) -> str:
  return value.replace("\\", "\\\\").replace("'", "\\'")


def format_keywords(keywords: list[str]) -> str:
  parts = ", ".join(f"'{ts_string(k)}'" for k in keywords)
  return f"[{parts}]"


def format_spot(spot: dict) -> list[str]:
  return [
    "      {",
    f"        placeName: '{ts_string(spot['place'])}',",
    f"        area: '{ts_string(spot['area'])}',",
    f"        category: SpotCategory.{spot['category']},",
    f"        description: '{ts_string(spot['desc'])}',",
    f"        stayMinutes: {spot['stay']},",
    "      },",
  ]


def build_ts() -> str:
  lines: list[str] = [
    "import { SpotCategory } from '@prisma/client';",
    "import { CatalogSeed } from './destination-types';",
    "",
    "export const CATALOG_SEED: CatalogSeed[] = [",
  ]
  for entry in prefecture_data:
    lines.append("  {")
    lines.append(f"    keywords: {format_keywords(entry['keywords'])},")
    lines.append("    spots: [")
    for spot in entry['spots']:
      lines.extend(format_spot(spot))
    lines.append("    ],")
    lines.append("  },")
  lines.append("];")
  lines.append("")
  return "\n".join(lines)


def main() -> None:
  target.write_text(build_ts(), encoding='utf-8')


if __name__ == '__main__':
  main()
